### ISSUE TITLE
Placing multiple cable with building gadget crashes

### ISSUE THREAD

**Issue by Jazriel** [refinedmods/refinedstorage#3201] opened 2021-12-31 16:43 UTC
### Describe the bug

The game crashes and the world becomes unplayable

Minecraft 1.16.5
Building Gadgets 3.8.2
Forge 36.2.20
Refined Storage 1.9.16

### How can we reproduce this bug or crash?

1. Place a cable
2. Select it with the building gadget (shift + right click)
3. Place multiple cables with the building gadget (right click)

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.20

### What Refined Storage version is this happening on?

1.9.16

### Relevant log output

```shell
The game crashed whilst ticking block entity
Error: java.lang.IllegalStateException: No network node present at BlockPos{X=-139, y=63, z=188}, consider removing the block at this position
Exit Code: -1
```

**Comment by Darkere** [comment] 2021-12-31 17:35
Duplicate of #3104

**Closed by Darkere** 2021-12-31 17:35 UTC
Labels: bug
