### ISSUE TITLE
storage drawers compatibility 

### ISSUE THREAD

**Issue by pr0c0** [refinedmods/refinedstorage#2826] opened 2021-01-12 20:18 UTC
#### Issue description:

lose of connect with external storage when connected to a drawer controller on server start

#### What happens:

when you log in the network doesn't see the drawer controller as being connected to the system

#### What you expected to happen:

have access to inventory 

#### Steps to reproduce:
1.exteral storage hooked up to drawer controller 
2. relog
3.lose of connection 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment] 2021-01-12 20:24
duplicate of #2636

**Closed** 2021-01-12 21:26 UTC
