### ISSUE TITLE
Cant Change Redstone Mode on Export on Server in ATM8

### ISSUE THREAD

**Issue by marco3102** [refinedmods/refinedstorage#3513] opened 2023-06-12 22:33 UTC
### Describe the bug

I cannot change the Redstone Mode on an Exporter on my Multiplayer Server. I can hear the button clicking but nothing is changing.

In singleplayer it works fine.
Temporary fix was changing it in Singleplayer because it kept the same Redstone Mode when I joined the Server and placed a new Exporter. Couldnt change the Redstone Mode still

### How can we reproduce this bug or crash?

1. Play All The Mods 8 
2. At some point in the Mid to End game try switching the Redstone Mode of an Exporter.

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.11

### What Refined Storage version is this happening on?

1.11.6

**Comment by marco3102** [comment] 2023-06-12 22:35
With the new Changed Mode through Singleplayer. Ive also noticed that the Exporter Ignore all Redstone Signals

**Comment by marco3102** [comment] 2023-06-12 23:32
Happens to all machines.

**Comment by Darkere** [comment] 2023-06-13 07:27
Duplicate of #3449

**Closed as not planned by Darkere** 2023-06-13 07:27 UTC
Labels: bug

**Comment by marco3102** [comment] 2023-06-14 20:23
Fake player settings in FTB Chunks fixed this issue
