### ISSUE TITLE
[1.16.4] Updates to external storage blocking grid access

### ISSUE THREAD

**Issue by Inzaniity** [refinedmods/refinedstorage#2840] opened 2021-01-17 21:27 UTC
#### Issue description: 
I was not able to access items in my grid (taken them out). Turns out my "cobblegen" updated an inventory (Storage Drawer) basically every second. As soon as this stopped I was able to access the network again. 

#### What happens: 
Updates on External Storage locks the grid in a way that you can't take items out of the system (putting items in works though)

#### What you expected to happen: 
pulling items out. 

#### Steps to reproduce:
1. Have an inventory connected to a storage bus in in/out mode, priority set to 1000
2. Have the in step 1 mentioned inventory update frequently by putting items into it (1 item a sec)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.36
- Refined Storage: 1.9.11
- Refined Storage Addons: 0.7.2 (including this because it also happens when using the portable crafting grid from the addons mod)

Does this issue occur on a server? Yes

**Comment by SirHecK** [comment] 2021-01-24 15:08
This is happening to me aswell with a digiminer feeding an enderchest which is contents is imported into the system then sent to exporters to machines.

**Comment by DrTurdle** [comment] 2021-01-28 14:34
I have a related issue where everytime my SP world gets reloaded I have to re-attach the external storage module to my drawer controller and set the prioirty.

If I don't then the RS system won't recognise the external storage and put all the items I've ported into the system just on the storage drives instead of my drawers (clogging up my system with cobbelstone).

**Comment by raoulvdberge** [comment] 2021-01-30 21:29
This is a duplicate of another issue

**Closed by raoulvdberge** 2021-01-30 21:29 UTC
