### ISSUE TITLE
Middle clicking (Sorting inventory) in Crafter dupes items in upgrade slots to the first slot in the Crafter.

### ISSUE THREAD

**Issue by jvgoch** [refinedmods/refinedstorage#2912] opened 2021-03-10 18:56 UTC
#### Issue description:
Middle clicking (Sorting inventory) in Crafter dupes items in upgrade slots to the first slot in the Crafter.
#### What happens:
Items get duped from upgrade slots on the side to the first pattern slot in the crafter.
#### What you expected to happen:
Nothing, or that the patterns get sorted in the same way the items would get sorted in an inventory.
#### Steps to reproduce:
1. Connect a Crafter to a RS system
2. Put Speed Upgrades in the upgrade slots
3. Middle click on the upgrade slots or the pattern slots
4. Items for the upgrade slots get duped the pattern slots

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.45
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment] 2021-03-10 19:05
Duplicate of #2833

**Closed by Darkere** 2021-03-10 19:05 UTC
