### ISSUE TITLE
Can't add recipe in Pattern Grid

### ISSUE THREAD

**Issue by mikiko90** [refinedmods/refinedstorage#2994] opened 2021-05-31 22:19 UTC
#### Issue description:
When I use JEI to search a recipe and insert it as a pattern in the grid, left-clicking the item in JEI won't open the recipe in JEI, will just let the grid become green. The only way I can turn around the problem is to right-click any item in JEI, then the left-click will work

#### What happens:
Can't left-click items in JEI when accessing Pattern Grid. Left-clicking an item will only highlight in green the 3x3 grid in Pattern Grid

#### What you expected to happen:
After accessing Patter Grid, look for an item in JEI, left-click it and add the recipe in the Pattern Grid to be saved as pattern

#### Steps to reproduce:
1. Access Pattern Grid
2. Left-click any item in JEI

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.0
- Refined Storage: 1.9.12

Does this issue occur on a server? [yes/no]
Both on a server and in singleplayer

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by ariosos** [comment] 2021-06-01 00:27
I noticed this, too. As a work-around, you can hover over the item, and press "R", or your recipe button. (You may have to click outside of the pattern grid GUI if the grid textbox is active).

**Comment by Darkere** [comment] 2021-06-01 06:43
Duplicate of #2982

**Closed by Darkere** 2021-06-01 06:43 UTC
