### ISSUE TITLE
[1.16.5] Server crashes when server is done loading world.

### ISSUE THREAD

**Issue by Gbergz** [refinedmods/refinedstorage#2884] opened 2021-02-19 17:34 UTC
#### Issue description:
Server crashes as soon as the world is done loading.

#### What happens:
Some ``FluidExternalStorage`` is crashing the server upon starting.

#### What you expected to happen:
That the server starts normally, no issues.

#### Steps to reproduce:
1. Start Server
2. Wait for it to load world
3. World loaded.
... Crash

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.25
- Refined Storage: 1.9.12

Modpack: TNP Limitless 3 | [v1.9.5](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/files/3209574)

Does this issue occur on a server? **Yes, yes it does.**

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/Gbergz/06d9e2acfc017751e68535ffa2673088

**Comment by Darkere** [comment] 2021-05-13 10:45
Duplicate of #2744

**Closed by Darkere** 2021-05-13 10:45 UTC
