### ISSUE TITLE
Refined storage crash with Electrodynamics

### ISSUE THREAD

**Issue by Column01** [refinedmods/refinedstorage#3147] opened 2021-11-23 03:40 UTC
#### Issue description:

When refined storage and Electrodynamics are installed together, the client crashes when loading

#### What happens:

Client crashes during load

#### What you expected to happen:

The client shouldn't crash

#### Steps to reproduce:
1. Install Refined Storage (**1.9.16**)
2. Install Electrodynamics (**0.5.0**)
3. Launch game and crash

#### Version (make sure you are on the latest version before reporting):

- Minecraft: `1.16.5`
- Forge: `36.2.8`
- Refined Storage: `1.9.16`

Does this issue occur on a server? [yes/no]

No

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here](https://paste.ee/p/qIozU)

**Comment by Darkere** [comment] 2021-11-23 07:43
Duplicate of #3129

**Closed by Darkere** 2021-11-23 07:43 UTC
