### ISSUE TITLE
Vanishing Patterns/Recipes.

### ISSUE THREAD

**Issue by Freakyman403** [refinedmods/refinedstorage#3577] opened 2023-10-20 04:06 UTC
### Describe the bug

I am submitted this issue to both Mekanism and Extra Storage as the issue also involved their mods.

But for some reason Mekanism Pipes/Cables cause patterns to vanish and any other pattern stored in the crafter will vanish,
all other items from mekanism so far remain untouched if place in different pattern storages.

### How can we reproduce this bug or crash?

Create Pattern for 4 of the tiered Universal Pipes/Cables
Place in Crafter for RS/ES
Restart Server - Sometimes takes 2 Restarts for issue to show.
Recipes vanished.

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.1.3

### What Refined Storage version is this happening on?

refinedstorage-1.12.3.jar

**Comment by raoulvdberge** [comment] 2023-11-04 20:35
Hi, thank you for reporting. I will be investigating this for the next RS version.

**Comment by raoulvdberge** [comment] 2023-11-05 16:52
Unfortunately, I can't reproduce this issue.
Please send us better reproduction steps. 
The log output is missing as well. If this happens again, please send us the log output.

**Closed as completed by raoulvdberge** 2023-11-05 16:52 UTC
Labels: bug
