### ISSUE TITLE
JEI 'move items' button is always enabled

### ISSUE THREAD

**Issue by Spongman** [refinedmods/refinedstorage#2237] opened 2019-05-13 03:45 UTC
.. and it doesn't show unavailable items.

is this a bug? i'm pretty sure AE2's crafting grid supports only enabling JEI's 'Move Items' button when the required ingredients are available.

if this is not a bug, when exactly is the 'move items' button disabled? JEI has a feature that shows the missing items, without this, when you click 'move items' it end up showing the crafting grid without those items requiring you to have to navigate all the way back through the crafting tree in order to find the missing ingredient. a real pain in the ass IMO.

**Comment by Darkere** [comment] 2019-05-13 08:46
Duplicate of  #1048

**Comment by Spongman** [comment] 2019-05-13 15:38
Weird. Why was that issue locked?

I can think of precisely _zero_ instances where I’d prefer to be dropped into a partially-filled crafting grid - what use is that, anyway? In _every_ instance where I’m trying to craft a thing, I’d much rather be able to see what’s missing and be able to click to see the recipe of one of the missing pieces.

From #1048, It seems like some others agree with me. Maybe this could be an option?

Is it that this functionally is difficult to implement?

**Comment by raoulvdberge** [comment] 2019-05-13 15:53
It's locked because I said I have no intentions of implementing this feature (see other issue for reason), yet people keep necro-posting on the issue.

**Comment by Darkere** [comment] 2019-05-13 16:15
You want this when the crafting recipe contains items with NBT for example. It will show as missing even when you have it. Or when you still have to pick up one of the ingredients from somewhere else. 

I remember that there was the issue that you can't have both the button enabled and show missing ingredients. Although that was years ago, no idea how it is today.

**Comment by Spongman** [comment] 2019-05-13 18:01
wouldn't this NBT issue be handled by a mod's subtype registry?

IMHO the default should be to imitate the default JEI behavior, and provide an override if you want to force an incomplete recipe into the crafting grid. personally, the NBT issue comes up so rarely that it's not a problem, however the incomplete recipe (and not showing the missing ingredients) issue happens so often as to make RS nearly unusable for me, which is a real shame :(

**Comment by ProxyPlayerHD** [comment] 2019-05-28 14:08
it should just handle JEI like any other crafting table.

it's really annoying and inconvenient that that really useful feature of JEI is just useless with the crafting grid.

**Comment by raoulvdberge** [comment] 2019-05-28 15:06
Enough now, point has come across.

**Comment by raoulvdberge** [comment] 2019-05-28 15:07
It's clearly marked as just "enhancement", which means this feature will be added at some point hopefully.

**Comment by raoulvdberge** [comment] 2020-09-25 19:00
Implemented for mc 1.16.3

**Closed by raoulvdberge** 2020-09-25 19:00 UTC
Labels: Enhancement
