### ISSUE TITLE
Error rendering while using Shader

### ISSUE THREAD

**Issue by TruthOriginem** [refinedmods/refinedstorage#2923] opened 2021-03-25 17:18 UTC
#### Issue description:
The block rendering is super wired and I set experimentalForgeLightPipelineEnabled = true

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.5
- Forge:36.1.2
- Refined Storage:1.9.12
![Snipaste_2021-03-26_01-18-22](https://user-images.githubusercontent.com/21058603/112515382-2eee9100-8dd1-11eb-9415-78a68704999d.png)

**Comment by Darkere** [comment] 2021-03-25 17:19
Duplicate of #2919

**Closed by Darkere** 2021-03-25 17:19 UTC
