### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by BraxtonMDevelops** [refinedmods/refinedstorage#2907] opened 2021-03-08 09:08 UTC
For the crafter manager have a button that lets me decide if i want to search between the crafters i have or the patterns i have. I've alwyas found it kind of infuriating that if i shiftclick i put my pattern into the first crafter no matter what it is.  Being able to filter them would be useful

**Comment by Darkere** [comment] 2021-03-08 09:10
Duplicate of #2102

**Closed by Darkere** 2021-03-08 09:10 UTC
