### ISSUE TITLE
Crash When pressing shift on Cave Facotry modpack.

### ISSUE THREAD

**Issue by HEROgold** [refinedmods/refinedstorage#3126] opened 2021-11-07 12:53 UTC
#### Issue description:
When i try to press shift inside a pattern grid, my games freezes for a few seconds, saves the world and then closes itself.

#### What happens:
See description
#### What you expected to happen:
I expect the game to not crash when holding shift, so i can quickly put away items in my storage.

#### Steps to reproduce:
1. Open pattern terminal,
2. Press shift
3. Crash
4.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.8
- Refined Storage: 1.9.13

Does this issue occur on a server? [yes/no]
no

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/Hkq56mNx
[pastebin/gist/etc link here]

**Comment by Darkere** [comment] 2021-11-07 13:59
Duplicate of #3110

**Closed by Darkere** 2021-11-07 13:59 UTC
