### ISSUE TITLE
[1.12.2] IC2ex Fluid Cell, Fluid Grid bug

### ISSUE THREAD

**Issue by a2y4** [refinedmods/refinedstorage#2291] opened 2019-08-04 13:39 UTC
#### Issue description:
When I try to put an IC2ex liquid cell into the Fluid Grid, it only recognizes one liquid.

#### What happens:
You can get one empty cell.

#### Steps to reproduce:
1. Introduce Refined Storage and IC2ex.
2. Set up "Controller", "Fluid Grid", "Disk Drive" and "Fluid Storage Disk"
3. Prepare two or more Ic2ex liquid cells
4. Shift or right click to enter Fluid Grid
...

![grid](https://user-images.githubusercontent.com/53612225/62424225-eb7c7600-b706-11e9-9120-0b545c6c0709.gif)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14,23,5,2838
- Refined Storage: 1.6.15
- (IC2ex): 2.8.170-ex112

**Comment by zotmer** [comment] 2019-11-26 13:57
I also have this issue. It is related not only to IC2ex fluid cell but to every single **stackable** fluid container from any mod.

**Comment by Darkere** [comment] 2021-01-31 15:07
Duplicate of #2187

**Closed by Darkere** 2021-01-31 15:07 UTC
Labels: Bug
