### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by y4ndex1** [refinedmods/refinedstorage#2824] opened 2021-01-12 10:08 UTC
#### Issue description:
my game crashes
#### What happens:
first when i enter to my world everything is fine expect my RF setup, power rans out even tho i am charging the controller, and when i open the crafting grid my game goes bye bye

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: latest
- Refined Storage: latest
Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:
https://hastebin.com/neripukuwe.rb

**Comment by Darkere** [comment] 2021-01-12 10:35
latest is not a version!!!!!

Power is not affected by this bug. Make sure you are giving the controller enough power, also check that your power source is actually getting power to the controller. 

Duplicate of #2811 


PS: There is a custom build floating around in discord in case this crash happens very frequently.

**Closed** 2021-01-12 12:18 UTC
