### ISSUE TITLE
Portable grid accumulates/retains nbt data until it can't be opened from inventory

### ISSUE THREAD

**Issue by PORTB** [refinedmods/refinedstorage#2820] opened 2021-01-10 11:36 UTC
#### Issue description:
The portable grid appears to retain nbt data of items that have been put into it, even when the disk in it is removed.
#### What happens:
Minecraft does not like the large amount of nbt data that is accumulated and will not allow the player to open the grid without placing it down and clicking on it. I have not experienced this in the 1.12 version
#### What you expected to happen:
The portable grid should not accumulate nbt, causing it to be unable to be opened without placing it down. 

#### Steps to reproduce:
Use the vanilla minecraft command `/data get entity @p Inventory[0].tag` (with the portable grid in the first hotbar slot with nothing else in your inventory to ensure the nbt data for the grid is shown) to view nbt of the item

Test 1
1. Open portable grid and put an item storage disk in and observe nbt using command.
2. Put some items in (e.g. 64 stone) and observe nbt.
3. Remove the items and observe nbt. You should notice it is almost exactly the same as with the stone in the disk.

Test 2
1. Open portable grid and put an item storage disk in and observe nbt using command.
2. Put some items in (e.g. 64 stone) and observe nbt.
3. Remove the disk and observe nbt. You should notice that it is almost exactly the same as with the disk in it.

The grid adds more data to the nbt for every unique stack inserted into it. This can quickly cause the nbt to become very large, especially with unstackable items such as bees in jars/cages (from productive/resourceful bees), which have almost 50 nbt tags that get added to the nbt of the portable grid. 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: 35.1.13
- Refined Storage: 1.9.11

Does this issue occur on a server? No

#### If a (crash)log is relevant for this issue, link it here:
Nil

**Comment by Darkere** [comment] 2021-01-10 13:39
Duplicate of #2765

**Closed** 2021-01-30 21:25 UTC
