### ISSUE TITLE
Move Item Missing Item

### ISSUE THREAD

**Issue by Tbrowning56** [refinedmods/refinedstorage#3303] opened 2022-05-17 00:17 UTC
### Describe the bug

I created a refined storage system with a controller, disk drive, 3x 4k storage disk, crafting grid, pattern grid and a wireless transmitter. I moved all my blocks into the storage and created a wireless crafting grid and linked it to the controller. 

Now on certain items it won't let me craft them from the JEI on the right side even when I have the items in my storage. When I hover over the move items + it says "missing items"
![mcissue](https://user-images.githubusercontent.com/87878338/168702342-74b43a17-f84d-42ab-a02f-1517d1ee01b7.png)

### How can we reproduce this bug or crash?

1. Create an RF system with 3x 4k storage disk and a wireless crafting grid
2. Insert items used to craft other items into the storage, especially other Refined storage or Mekanism parts
3. See if its doing the same "missing item" issue

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.19

### What Refined Storage version is this happening on?

refinedstorage-1.10.2

**Comment by Darkere** [comment] 2022-05-26 11:43
Duplicate of #3302

**Closed as not planned by Darkere** 2022-05-26 11:43 UTC
Labels: bug, duplicate
