### ISSUE TITLE
Storage disks disappeared

### ISSUE THREAD

**Issue by leviathan13** [refinedmods/refinedstorage#3299] opened 2022-05-09 20:01 UTC
### Describe the bug

My main storage disks disappeared while playing.

### How can we reproduce this bug or crash?

Unknown, but it's possible that teleporting might be a factor (I was teleporting both through Journey map waypoints and vanilla nether portals). My home base with my main storage was also forceloaded with [chunk loaders](https://www.curseforge.com/minecraft/mc-mods/chunk-loaders).

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.0

### What Refined Storage version is this happening on?

1.10.2

### Relevant log output

```shell
[09mag2022 20:36:08.409] [Server thread/ERROR] [com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeManager/]: Could not read network node
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.m_8895_()" because "overworld" is null
	at com.refinedmods.refinedstorage.apiimpl.API.getStorageDiskManager(API.java:207) ~[refinedstorage-1.10.2.jar%2394!/:1.10.2]
	at com.refinedmods.refinedstorage.apiimpl.network.node.storage.StorageNetworkNode.loadStorage(StorageNetworkNode.java:157) ~[refinedstorage-1.10.2.jar%2394!/:1.10.2]
	at com.refinedmods.refinedstorage.apiimpl.network.node.storage.StorageNetworkNode.read(StorageNetworkNode.java:152) ~[refinedstorage-1.10.2.jar%2394!/:1.10.2]
	at com.refinedmods.refinedstorage.setup.CommonSetup.readAndReturn(CommonSetup.java:143) ~[refinedstorage-1.10.2.jar%2394!/:1.10.2]
	at com.refinedmods.refinedstorage.setup.CommonSetup.lambda$onCommonSetup$7(CommonSetup.java:84) ~[refinedstorage-1.10.2.jar%2394!/:1.10.2]
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeManager.load(NetworkNodeManager.java:59) ~[refinedstorage-1.10.2.jar%2394!/:1.10.2]
	at com.refinedmods.refinedstorage.apiimpl.API.lambda$getNetworkNodeManager$1(API.java:134) ~[refinedstorage-1.10.2.jar%2394!/:1.10.2]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164868_(DimensionDataStorage.java:70) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164858_(DimensionDataStorage.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164861_(DimensionDataStorage.java:39) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at com.refinedmods.refinedstorage.apiimpl.API.getNetworkNodeManager(API.java:132) ~[refinedstorage-1.10.2.jar%2394!/:1.10.2]
	at com.refinedmods.refinedstorage.blockentity.NetworkNodeBlockEntity.m_6339_(NetworkNodeBlockEntity.java:75) ~[refinedstorage-1.10.2.jar%2394!/:1.10.2]
	at net.minecraft.world.level.chunk.LevelChunk.m_142169_(LevelChunk.java:345) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_196900_(ChunkSerializer.java:414) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_62952_(LevelChunk.java:417) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$protoChunkToFullChunk$29(ChunkMap.java:815) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-4.1.27.jar%2333!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2333!/:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-4.1.27.jar%2333!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$protoChunkToFullChunk$30(ChunkMap.java:796) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:198) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:532) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:163) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:540) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:176) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:129) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.world.level.Level.m_6522_(Level.java:169) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:123) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.world.level.Level.m_6325_(Level.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.server.level.ServerLevel.m_8602_(ServerLevel.java:1169) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$ChunkTracker.add(ChunkLoaderUtil.java:86) ~[chunkloaders-1.1.12-mc1.18.jar%2362!/:?]
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$ChunkTracker.lambda$read$0(ChunkLoaderUtil.java:124) ~[chunkloaders-1.1.12-mc1.18.jar%2362!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177) ~[?:?]
	at java.util.Spliterators$LongArraySpliterator.forEachRemaining(Spliterators.java:1159) ~[?:?]
	at java.util.Spliterator$OfLong.forEachRemaining(Spliterator.java:775) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$ChunkTracker.read(ChunkLoaderUtil.java:124) ~[chunkloaders-1.1.12-mc1.18.jar%2362!/:?]
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$2.lambda$deserializeNBT$0(ChunkLoaderUtil.java:61) ~[chunkloaders-1.1.12-mc1.18.jar%2362!/:?]
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.2-40.1.0-universal.jar%23109!/:?]
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$2.deserializeNBT(ChunkLoaderUtil.java:61) ~[chunkloaders-1.1.12-mc1.18.jar%2362!/:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:127) ~[forge-1.18.2-40.1.0-universal.jar%23109!/:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:35) ~[forge-1.18.2-40.1.0-universal.jar%23109!/:?]
	at net.minecraftforge.common.util.WorldCapabilityData.read(WorldCapabilityData.java:37) ~[forge-1.18.2-40.1.0-universal.jar%23109!/:?]
	at net.minecraftforge.common.util.WorldCapabilityData.load(WorldCapabilityData.java:28) ~[forge-1.18.2-40.1.0-universal.jar%23109!/:?]
	at net.minecraft.server.level.ServerLevel.lambda$initCapabilities$22(ServerLevel.java:1494) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164868_(DimensionDataStorage.java:70) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164858_(DimensionDataStorage.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164861_(DimensionDataStorage.java:39) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.server.level.ServerLevel.initCapabilities(ServerLevel.java:1494) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:227) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:355) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:316) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23105!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by leviathan13** [comment] 2022-05-09 20:02
[latest - copy.log](https://github.com/refinedmods/refinedstorage/files/8654962/latest.-.copy.log)

Whole log.

**Comment by raoulvdberge** [comment] 2022-05-28 12:14
Not caused by RS I think @Darkere  ? Closing.

**Closed as completed by raoulvdberge** 2022-05-28 12:14 UTC
Labels: bug

**Comment by Darkere** [comment] 2022-05-28 12:17
The chunkloader mod is changing the load order in which world data is loaded. I've reported and they will fix it when they get time.
