### ISSUE TITLE
Remaining crafting time negative

### ISSUE THREAD

**Issue by CraftalotReloaded** [refinedmods/refinedstorage#2267] opened 2019-06-20 13:37 UTC
At random the remaining crafting time can be negative 
![image](https://user-images.githubusercontent.com/39203645/59853513-51888600-9371-11e9-8970-707da84dc0e8.png)

**Comment by raoulvdberge** [comment] 2020-06-27 10:19
Closing this as I can't reproduce this.

**Closed by raoulvdberge** 2020-06-27 10:19 UTC
Labels: Bug
