### ISSUE TITLE
Autocrafting with NBT doesnt' work (Immersive Engeneering Plates) (12.2)

### ISSUE THREAD

**Issue by Therealcrazyone** [refinedmods/refinedstorage#2565] opened 2020-06-09 22:05 UTC
#### Issue description:
Autocrafting a recipe with an item that takes damage because of the craft doesn't work
#### What happens:
To craft wires from IE you need a plate and a wire cutter/shears, when I try to autocraft it says it needs as many cutters as my order, aka 100 wires = 100 wire cutters
#### What you expected to happen:
It should reuse the same cutters and let them be damaged 
#### Steps to reproduce:
1.Make a pattern (I used actual items from the system) 
2.Turn on oredic function 
3.Order Wires 
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:12.2
- Forge:14.23.5.2854
- Refined Storage:1.6.16

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment] 2020-06-09 22:21
Duplicate of #2510

**Closed** 2020-06-10 01:33 UTC
