### ISSUE TITLE
Processing recipe ingredients get inserted in an order different from the patern

### ISSUE THREAD

**Issue by snydej** [refinedmods/refinedstorage#2661] opened 2020-08-24 09:06 UTC
#### Issue description:
For infusion style crafts I had previously been able to rely on it being that the first item in the pattern would end up in the first slot of the inventory pointed to by the crafter. This is useful because at least one very common mod (Draconic Evolution, I don't know if there are others) has recipes where an item may need to go in the center for one recipe but on the outside in another. Filters won't work to route items in these cases. An elegant solution is to transport items to the center of the infusion setup with a higher priority than to the outside and to put the item that needs to go in the center first in the pattern. Somewhere between the version of RS I was playing in my 1.10 world and RS 1.6.15 for Minecraft 1.12.2 this behavior changed to something much harder to engineer around.

#### What happens:
The order in which items are added seems to be independent of how they are in the pattern. It appears to be consistent but not easily predictable (it's not sorting by id, for example).

#### What you expected to happen:
It would be nice if the order in which the items went into slots was the same as the order in the pattern.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Refined Storage: 1.6.15

**Comment by Darkere** [comment] 2020-08-24 09:32
Duplicate of https://github.com/refinedmods/refinedstorage/issues/1937

**Closed** 2020-09-05 13:10 UTC
