### ISSUE TITLE
Refined Storage lags when viewing certain recipes with JEI 2, Electric Boogaloo

### ISSUE THREAD

**Issue by Twisted-Code** [refinedmods/refinedstorage#3495] opened 2023-04-13 12:14 UTC
### Describe the bug

so I saw #3406, and based on the [branch history of develop](https://github.com/refinedmods/refinedstorage/commits/develop), it looks like it should be fixed as of [1.11.3](https://github.com/refinedmods/refinedstorage/releases/tag/v1.11.3), right? I'm playing All The Mods 8  (ATM8 for  short) which is running RS version 1.11.5, but I still get a noticeable amount of lag, at least under some circumstances, when viewing recipes such as cover crafting recipes. It doesn't happen constantly, seems like it might just be the first time I view the recipe in a given session, but it causes the entire game to stutter when it happens so I still kind of want to see it resolved if we can track it down.

### How can we reproduce this bug or crash?

1. Install ATM 8 (or presumably any other pack that has a lot of custom blocks; I think the issue may be triggered by having a lot of possible cover recipes.)
2. view any cover recipe by choosing "uses" for something like, IDK, clay block? I've seen it happen with `allthecompressed:clay_block_1x` and `supplementaries:flax_block`, for instance.
3. stutter stutter stutter.

These steps may be incomplete as even with them I'm not able to get it to happen every time, but it's definitely reproducible with some amount of consistency.

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.6

### What Refined Storage version is this happening on?

1.11.5

**Comment by P3rf3ctXZer0** [comment] 2023-04-15 03:35
I too have this exact issue I posted a video and got told I was self promoting but if it helps this is exactly what the bug looks like. (Forgive my cursing)

https://youtu.be/cWeVf2ubu5Q

This is not specificaly caused by JEI. I completely removed JEI and this is still happening.

**Comment by Twisted-Code** [comment] 2023-04-17 17:10
not quite the same issue; my issue is with viewing the item recipes in inventory, not the machines.
hey question: do you happen to have oculus installed in that instance, @P3rf3ctXZer0? I've been having rendering issues with that mod installed messing with other stuff in JEI/inventory, such as making all Productive Bees white (a known issue), so I'm going to try uninstalling that and if you have it maybe you should try the same? Oculus doesn't do anything much except add shaders anyway, and I can live without.

**Comment by Twisted-Code** [comment] 2023-05-07 12:29
Honestly this may be with JEI, I've had issues with other recipes that have "large"/commonly-used tags as inputs. A lot of things involving wood-related tags seem to similarly cause lag. I'm still investigating and need to make note of specific examples so I can report it to mezz/JEI, but it might not be you.

**Comment by raoulvdberge** [comment] 2023-11-04 21:31
Hi, this should be fixed indeed with the version you mentioned. If you have more info feel free to provide it.

**Closed as completed by raoulvdberge** 2023-11-04 21:31 UTC
Labels: bug
