### ISSUE TITLE
Projectred cell and gate inventory item models are causing crash when used for patterns

### ISSUE THREAD

**Issue by ethanmorton** [refinedmods/refinedstorage#3165] opened 2021-12-11 01:09 UTC
#### Issue description:
The game instantly crashes when I look at an inventory with a pattern for any gate or cell from Projectred

#### What happens:
Whenever I press shift with the pattern for a Projectred cell or gate visible, and it tries to show the item that the pattern will give, it freezes then crashes the game immediately

#### What you expected to happen:
Be able to see the item with the pattern when pressing shift in inventories or with it in hand

#### Steps to reproduce:
1. Create a pattern for a Projectred gate or cell using the pattern grid.
2. Press shift while the pattern is in hand, or visible in inventory, or attempt to put it into a crafter
3. the game will freeze for a second, then go to the "Saving World" screen, and the quit and provide a crash report

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 32.6.9
- Refined Storage: 1.9.16
- Modpack: FTB Oceanblock 1.9.0

Does this issue occur on a server? [yes/no]
not sure, I don't have a server

#### If a (crash)log is relevant for this issue, link it here:

Crash from a gate :: https://pastebin.com/UmT6zHas
Crash fropm a cell :: https://pastebin.com/3ZxdJkDb

**Comment by Darkere** [comment] 2021-12-11 12:05
Duplicate of #3110

I believe project Red has put in a failsafe at this point, so it doesn't crash.

**Closed by Darkere** 2021-12-11 12:05 UTC
