### ISSUE TITLE
Ender Chest from EnderStorage breaks item retrieval

### ISSUE THREAD

**Issue by Beckfast1994** [refinedmods/refinedstorage#2865] opened 2021-02-03 22:43 UTC
#### Issue description: 
There seems to be some incompatibility with the mod EnderStorage. I was trying to use an Ender Chest from the EnderStorage mod as external storage and it caused my RS to stop allowing me to remove items. I've let them know about it as well and they suggested I report the issue to you guys. Here's that other issue thread: [https://github.com/TheCBProject/EnderStorage/issues/152#issue-800670954](https://github.com/TheCBProject/EnderStorage/issues/152#issue-800670954). Also I'm playing with the Enigmatica 6 modpack if that makes any difference.

#### What happens: 
When the Ender Chest is placed on an External Storage and I try to remove items through the crafting grid I can't take anything out. If I remove the Ender Chest everything works again.

#### What you expected to happen: 
The Ender Chest should work just like any regular chest and be usable as standard external storage with RS.

#### Steps to reproduce:
1. Place Ender Chest on External Storage
2. Try to remove any item from storage using RS interface
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.10
- Refined Storage: 1.9.11

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment] 2021-02-04 07:59
Duplicate of #2568

**Closed by Darkere** 2021-02-04 07:59 UTC
