### ISSUE TITLE
Tinker's construct Stencil Internal Server Crash

### ISSUE THREAD

**Issue by Therealcrazyone** [refinedmods/refinedstorage#2556] opened 2020-06-06 13:49 UTC
#### Issue description: 
When Shift Clicking the Stencil from Tinker's construct in the Crafting Grid it causes an internal server error. In my singleplayer game I was kicked to the multiplayer screen on the main menu

Edit: this also now happens while shift clicking a piston into the crafting grid

#### What happens:
When Shift Clicking the Stencil from Tinker's construct in the Crafting Grid it causes an internal server error. In my singleplayer game I was kicked to the multiplayer screen on the main menu
Edit: the piston caused an internal crash 
#### What you expected to happen: 
The recipe  from the stencil to be in the crafting grid

#### Steps to reproduce:
1.Open Crafting Grid
2. Search Stencil in JEI
3.Open the Stencil recipe
4. Shift click the little + 
...

#### Version (make sure you are on the latest version before reporting):
- Minecraft:1.12.2
- Forge:14.23.5.2854
- Refined Storage: 1.6.16

####Addons to RS:
-Refined Storage Addons 0.4.5
-Refined Storage Requestify 1.0.2-3
-Refined Avaritia-2.6.

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:
This is the latest log of me crashing the internal server by shift clicking pistons  
First time I shift clicked a piston in a recipe,second time I just shift clicked a piston.
[latest.log](https://github.com/refinedmods/refinedstorage/files/4740839/latest.log)

**Comment by Darkere** [comment] 2020-06-06 14:31
Please provide the latest.log where this error occurs.

**Comment by Therealcrazyone** [comment] 2020-06-06 19:08
> Please provide the latest.log where this error occurs.

I added a latest.log, I also found that this same bug works with pistons which is what I used for the Latest.log

**Comment by Darkere** [comment] 2020-06-06 19:20
Oh, I'm dumb. Duplicate of #1790

Pro-tip: You don't need to shift click the +. A regular click works just fine.

**Closed** 2020-06-06 19:51 UTC
