### ISSUE TITLE
Regulator Improvements: Craft-Only & Fill Container

### ISSUE THREAD

**Issue by cpriest** [refinedmods/refinedstorage#2932] opened 2021-04-02 04:02 UTC
#### Issue description:
The regulator is great, but it can only be set to keep 64 crafted.  The regulator when combined with a crafting card doesn't craft if the storage system can see the crafted material.

#### What happens:
Cannot increase auto-craft amount past 64, buttons don't work, setting the number directly doesn't work (reverts to 64).  Also, when combined with a crafting card, it will not craft the item if it can pull it from some attached inventory.

#### What you expected to happen:
Be able to set the auto-craft amount higher, ideally as high as desired or "until full."  Combined with crafter, ability to say only craft items for export.

On latest version included with ATM6 To The Sky

Does this issue occur on a server? yes

Thanks for a great mod!

**Comment by Darkere** [comment] 2021-04-11 10:05
Duplicate of #2586

**Closed by Darkere** 2021-04-11 10:05 UTC
