### ISSUE TITLE
Autocrafting issue

### ISSUE THREAD

**Issue by lol702702lol** [refinedmods/refinedstorage#3559] opened 2023-09-02 13:23 UTC
### Describe the bug

In my world, there's constantly something autocrafting with requesters. Till some days ago, everything went ok but we encountered an issue, causing the game to crash as soon as the wolrd is trying to load.

### How can we reproduce this bug or crash?

1.Have many autocrafting tasks running at the same time(at least that's what I suspect)
2.Eventually the game crashes

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.14

### What Refined Storage version is this happening on?

1.11.6

### Relevant log output

```shell
Description: Exception in server tick loop

java.lang.IllegalStateException: Bad!
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.node.NodeRequirements.getSingleItemRequirementSet(NodeRequirements.java:93) ~[refinedstorage-1.11.6.jar%23801!/:1.11.6] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.node.CraftingNode.update(CraftingNode.java:50) ~[refinedstorage-1.11.6.jar%23801!/:1.11.6] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.CraftingTask.update(CraftingTask.java:189) ~[refinedstorage-1.11.6.jar%23801!/:1.11.6] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.updateTasks(CraftingManager.java:218) ~[refinedstorage-1.11.6.jar%23801!/:1.11.6] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:182) ~[refinedstorage-1.11.6.jar%23801!/:1.11.6] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:181) ~[refinedstorage-1.11.6.jar%23801!/:1.11.6] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onLevelTick(NetworkListener.java:17) ~[refinedstorage-1.11.6.jar%23801!/:1.11.6] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.__NetworkListener_onLevelTick_LevelTickEvent.invoke(.dynamic) ~[refinedstorage-1.11.6.jar%23801!/:1.11.6] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:820) ~[forge-1.19.2-43.2.14-universal.jar%23904!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[client-1.19.2-20220805.130853-srg.jar%23899!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack,pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23899!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack,pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23899!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin,pl:mixin:APP:mixins.essential.json:server.integrated.MixinIntegratedServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23899!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack,pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23899!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack,pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 5444407688 bytes (5192 MiB) / 9797894144 bytes (9344 MiB) up to 16844324864 bytes (16064 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 65461.19
	Virtual memory used (MB): 22781.38
	Swap memory total (MB): 32768.00
	Swap memory used (MB): 23.96
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16064m -Xms256m
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:saturn, mod:betterdungeons, mod:supermartijn642configlib (incompatible), mod:paucal (incompatible), mod:quarryplus, mod:simplemagnets (incompatible), mod:botarium, mod:integratedterminals (incompatible), mod:paragon, mod:entitycollisionfpsfix (incompatible), mod:rubidium (incompatible), mod:modnametooltip (incompatible), mod:ironjetpacks (incompatible), mod:laserio (incompatible), mod:ctm (incompatible), mod:reauth (incompatible), mod:modernfix (incompatible), mod:evilcraft (incompatible), mod:yungsapi, mod:powah (incompatible), mod:gateways (incompatible), mod:cabletiers (incompatible), mod:rangedpumps, mod:wstweaks (incompatible), mod:shrink (incompatible), mod:universalgrid (incompatible), mod:darkutils (incompatible), mod:apotheosis (incompatible), mod:clickadv (incompatible), mod:balm (incompatible), mod:jeresources, mod:cloth_config (incompatible), mod:shetiphiancore (incompatible), mod:ctov (incompatible), mod:structure_gel, mod:advancementplaques (incompatible), mod:packmenu (incompatible), mod:alltheores (incompatible), mod:industrialforegoing (incompatible), mod:torchmaster (incompatible), mod:handcrafted, mod:repurposed_structures, mod:botanytrees (incompatible), mod:ironfurnaces (incompatible), mod:structurecompass, mod:mcwtrpdoors, mod:supermartijn642corelib (incompatible), mod:botania (incompatible), mod:resourcefulconfig, mod:spark (incompatible), mod:curios, mod:corail_woodcutter, mod:oculus, mod:advgenerators, mod:measurements, mod:yungsextras, mod:angelring (incompatible), mod:tombstone, mod:antighost (incompatible), mod:naturesaura (incompatible), mod:constructionwand, mod:mcwroofs, mod:littlelogistics (incompatible), mod:cfm (incompatible), mod:fastleafdecay, mod:bettermineshafts, mod:geckolib3 (incompatible), mod:sfm (incompatible), mod:vitalize, mod:mcwlights, mod:crafting_on_a_stick (incompatible), mod:essential (incompatible), mod:smartbrainlib, mod:elytraslot, mod:nomowanderer (incompatible), mod:rechiseled (incompatible), mod:harvestwithease, mod:attributefix (incompatible), mod:tesseract (incompatible), mod:caelus (incompatible), mod:bdlib, mod:allthecompressed (incompatible), mod:naturescompass (incompatible), mod:jumpboat (incompatible), mod:libx, mod:compactmachines, mod:botanypots (incompatible), mod:phosphophyllite (incompatible), mod:farmingforblockheads (incompatible), mod:pneumaticcraft, mod:additional_lights, mod:extradisks, mod:edivadlib, mod:forge, mod:silentgear, mod:mythicbotany, mod:integratedcrafting (incompatible), mod:dungeons_arise, mod:alchemistry (incompatible), mod:cofh_core, mod:thermal, mod:thermal_integration, mod:redstone_arsenal, mod:thermal_innovation, mod:thermal_foundation, mod:thermal_locomotion, mod:thermal_dynamics (incompatible), mod:systeams (incompatible), mod:simplebackups, mod:theoneprobe (incompatible), mod:terrablender, mod:mousetweaks, mod:immersiveengineering (incompatible), mod:nochatreports (incompatible), mod:allthemodium (incompatible), mod:spectrelib (incompatible), mod:domum_ornamentum, mod:kotlinforforge (incompatible), mod:flywheel (incompatible), mod:integrateddynamics (incompatible), mod:integratednbt (incompatible), mod:itemcollectors (incompatible), mod:croptopia (incompatible), mod:thermal_cultivation, mod:bhc (incompatible), mod:polymorph, mod:justenoughprofessions, mod:autoreglib (incompatible), mod:securitycraft, mod:almostunified (incompatible), mod:jei (incompatible), mod:mekanism, mod:gravitationalmodulatingunittweaks (incompatible), mod:pipez (incompatible), mod:entityculling, mod:structurize, mod:fastfurnace (incompatible), mod:appleskin, mod:lootr (incompatible), mod:connectedglass (incompatible), mod:occultism, mod:allthetweaks (incompatible), mod:byg, mod:corgilib (incompatible), mod:aquaculture, mod:extremesoundmuffler (incompatible), mod:cosmeticarmorreworked (incompatible), mod:ad_astra (incompatible), mod:ad_astra_giselle_addon (incompatible), mod:tetra (incompatible), mod:tetranomicon, mod:rsrequestify (incompatible), mod:hexerei (incompatible), mod:cyclopscore (incompatible), mod:blue_skies, mod:alchemylib (incompatible), mod:betterwitchhuts, mod:netherportalfix (incompatible), mod:aiotbotania, mod:advancedperipherals (incompatible), mod:utilitix, mod:naturalist, mod:healthoverlay (incompatible), mod:betteroceanmonuments, mod:connectivity (incompatible), mod:sophisticatedcore (incompatible), mod:glassential (incompatible), mod:controlling (incompatible), mod:prism, mod:placebo (incompatible), mod:dankstorage (incompatible), mod:mixinextras (incompatible), mod:potionsmaster (incompatible), mod:bookshelf (incompatible), mod:sophisticatedbackpacks (incompatible), mod:littlecontraptions (incompatible), mod:buildinggadgets (incompatible), mod:framedblocks, mod:mcwdoors, mod:railways (incompatible), mod:mekanismgenerators, mod:dummmmmmy (incompatible), mod:absentbydesign (incompatible), mod:twilightforest (incompatible), mod:mob_grinding_utils (incompatible), mod:experiencebugfix, mod:rsinfinitybooster (incompatible), mod:adtetra, mod:chipped (incompatible), mod:mcwbridges, mod:farmersdelight, mod:tempad (incompatible), mod:hostilenetworks (incompatible), mod:entangled (incompatible), mod:endertanks (incompatible), mod:commoncapabilities (incompatible), mod:crashutilities (incompatible), mod:getittogetherdrops, mod:mcwfences, mod:fuelgoeshere, mod:wirelesschargers (incompatible), mod:simplylight (incompatible), mod:modelfix (incompatible), mod:dpanvil (incompatible), mod:blockui, mod:multipiston, mod:spititout, mod:tiab (incompatible), mod:villagertools (incompatible), mod:thermal_expansion, mod:integratedtunnels (incompatible), mod:mysticalcustomization (incompatible), mod:elevatorid (incompatible), mod:ftbultimine (incompatible), mod:betterstrongholds, mod:runelic (incompatible), mod:resourcefullib (incompatible), mod:spirit (incompatible), mod:mekanismtools, mod:inventoryprofilesnext (incompatible), mod:deeperdarker, mod:architectury (incompatible), mod:bambooeverything (incompatible), mod:ftblibrary (incompatible), mod:ftbic (incompatible), mod:myrtrees (incompatible), mod:findme (incompatible), mod:ftbteams, mod:ftbranks (incompatible), mod:ftbessentials (incompatible), mod:computercraft (incompatible), mod:energymeter (incompatible), mod:moreoverlays (incompatible), mod:productivebees, mod:hexal (incompatible), mod:trashcans (incompatible), mod:inventoryessentials (incompatible), mod:bwncr (incompatible), mod:observable (incompatible), mod:letmedespawn (incompatible), mod:controllable (incompatible), mod:yeetusexperimentus, mod:gamemenumodoption, mod:voidtotem (incompatible), mod:darkmodeeverywhere (incompatible), mod:betteradvancements (incompatible), mod:rhino (incompatible), mod:kubejs (incompatible), mod:biggerreactors (incompatible), mod:rootsclassic, mod:cucumber (incompatible), mod:trashslot (incompatible), mod:jmi (incompatible), mod:blueflame, mod:sophisticatedstorage (incompatible), mod:additionallanterns (incompatible), mod:itemfilters (incompatible), mod:ftbquests (incompatible), mod:platforms (incompatible), mod:travelanchors, mod:ensorcellation, mod:create, mod:ponderjs (incompatible), mod:waystones (incompatible), mod:thermal_extra (incompatible), mod:fastsuite (incompatible), mod:clumps (incompatible), mod:journeymap (incompatible), mod:comforts, mod:artifacts, mod:configured (incompatible), mod:dimstorage, mod:myserveriscompatible (incompatible), mod:dungeoncrawl, mod:defaultsettings, mod:charginggadgets (incompatible), mod:lazydfu (incompatible), mod:mcjtylib (incompatible), mod:rftoolsbase (incompatible), mod:xnet (incompatible), mod:rftoolspower (incompatible), mod:rftoolsbuilder (incompatible), mod:deepresonance (incompatible), mod:xnetgases (incompatible), mod:rftoolsstorage (incompatible), mod:rftoolscontrol (incompatible), mod:betterdeserttemples, mod:mahoutsukai, mod:farsight_view (incompatible), mod:toastcontrol (incompatible), mod:mininggadgets (incompatible), mod:hexcasting (incompatible), mod:ftbchunks (incompatible), mod:xycraft_core, mod:xycraft_world, mod:xycraft_override, mod:mysticalagriculture (incompatible), mod:mysticalagradditions (incompatible), mod:craftingtweaks (incompatible), mod:tetrasdelight (incompatible), mod:rftoolsutility (incompatible), mod:libipn (incompatible), mod:sebastrnlib (incompatible), mod:appliedcooking (incompatible), mod:refinedcooking (incompatible), mod:refinedstorage, mod:extrastorage, mod:ae2 (incompatible), mod:aeinfinitybooster (incompatible), mod:cookingforblockheads (incompatible), mod:rebornstorage (incompatible), mod:merequester (incompatible), mod:patchouli (incompatible), mod:ars_nouveau, mod:delightful (incompatible), mod:ars_armiger, mod:ars_creo (incompatible), mod:ae2wtlib (incompatible), mod:elementalcraft (incompatible), mod:moonlight (incompatible), mod:eccentrictome, mod:toolbelt, mod:titanium (incompatible), mod:silentlib (incompatible), mod:ae2things (incompatible), mod:theurgy, mod:easy_villagers (incompatible), mod:iceberg (incompatible), mod:reliquary (incompatible), mod:quark (incompatible), mod:supplementaries (incompatible), mod:mutil (incompatible), mod:legendarytooltips (incompatible), mod:chemlib (incompatible), mod:pigpen (incompatible), mod:fastbench (incompatible), mod:fluxnetworks (incompatible), mod:ars_elemental, mod:enderchests (incompatible), mod:appbot (incompatible), mod:modonomicon, mod:sandbox, mod:quartz (incompatible), mod:minecolonies (incompatible), mod:pylons, mod:creeperoverhaul (incompatible), mod:ferritecore (incompatible), mod:engineersdecor, mod:solcarrot (incompatible), mod:functionalstorage (incompatible), mod:moredragoneggs (incompatible), mod:modularrouters, mod:asynclocator (incompatible), mod:charmofundying, mod:betterf3 (incompatible), mod:refinedstorageaddons, mod:appmek (incompatible), mod:ae2additions (incompatible), mod:megacells (incompatible), mod:expandability (incompatible), mod:morphtool (incompatible), mod:flickerfix, mod:createaddition (incompatible), Supplementaries Generated Pack, mod:maxhealthfix (incompatible), mod:despawntimers (incompatible), mod:starlight (incompatible), mod:fusion (incompatible), mod:enchdesc (incompatible), mod:useitemonblockevent (incompatible), mod:morered (incompatible), mod:rsgauges, mod:ding, mod:cupboard (incompatible), mod:undergarden, mod:serverconfigupdater (incompatible), mod:gunpowderlib (incompatible), mod:exchangers (incompatible), mod:matc, mod:ftbxmodcompat (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: forge-43.2.14
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.14.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.14.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.14.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.14.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.14.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar jcplugin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar essential-loader TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.12.0
		lowcodefml@null
		kotori_scala@2.13.10-build-10
```

**Comment by raoulvdberge** [comment] 2023-11-04 21:25
Duplicate of #3514

**Closed as completed by raoulvdberge** 2023-11-04 21:25 UTC
Labels: bug, duplicate
