### ISSUE TITLE
The game crashes constantly.

### ISSUE THREAD

**Issue by Prophet2002** [refinedmods/refinedstorage#3166] opened 2021-12-11 02:41 UTC
#### Steps to reproduce:
1. Install a mod.
2. Launch game.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.20
- Refined Storage: 1.9.17+214

Does this issue occur on a server? no

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/QjgxQBvK

**Comment by Darkere** [comment] 2021-12-11 12:04
Duplicate of #3129

**Closed by Darkere** 2021-12-11 12:04 UTC
