### ISSUE TITLE
Crafting Grid CTRL + CLICK ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Klowes** [refinedmods/refinedstorage#3442] opened 2022-12-27 16:16 UTC
### Describe the bug

CTRL + CLICK functionality on Crafting Grid only supports recipes with up to 9 input slots in JEI seemingly, this boots the player back to main menu.

### How can we reproduce this bug or crash?

Autocraft components for Create mod's mechanical crafter in JEI and CTRL + CLICK in the crafting grid where >9 mechanical crafters are required.

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

1.19.2-forge-43.1.57

### What Refined Storage version is this happening on?

refinedstorage-1.11.1

### Relevant log output

Client:

> [28Dec2022 08:42:46.086] [Render thread/INFO] [configured/]: Unloading synced configs from server
> [28Dec2022 08:42:46.086] [Render thread/INFO] [FluxNetworks/]: Released client Flux Networks cache
> [28Dec2022 08:42:46.086] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
> [28Dec2022 08:42:46.086] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
> [28Dec2022 08:42:46.086] [Render thread/INFO] [mezz.jei.forge.startup.ClientLifecycleHandler/]: Stopping JEI
> [28Dec2022 08:42:46.089] [Render thread/INFO] [minecolonies/]: Removed all colony views
> [28Dec2022 08:42:51.774] [Render thread/WARN] [structurize/]: Client logged off. Resetting Pack Meta and Reloading State
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Shire
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Desert Oasis
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Pagoda
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Minecolonies Original
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Caledonia
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Incan
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Warped Netherlands
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Dark Oak Treehouse
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Urban Birch
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Medieval Oak
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Medieval Birch
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Cavern
> [28Dec2022 08:42:51.775] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Space Wars
> [28Dec2022 08:42:51.776] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Medieval Spruce
> [28Dec2022 08:42:51.776] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Jungle Treehouse
> [28Dec2022 08:42:51.776] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Nordic Spruce
> [28Dec2022 08:42:51.776] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Medieval Dark Oak
> [28Dec2022 08:42:51.776] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Urban Savanna
> [28Dec2022 08:42:51.776] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Stalactite Caves
> [28Dec2022 08:42:51.776] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Lost Mesa City
> [28Dec2022 08:42:51.776] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: Fortress
> [28Dec2022 08:42:51.776] [Structurize IO Worker #0/INFO] [structurize/]: Registered structure pack: OriginalPoster
> [28Dec2022 08:42:51.776] [Structurize IO Worker #0/WARN] [structurize/]: Finished discovering Client Structure packs

Server:

> [08:42:46] [Netty Server IO #22/WARN] [co.co.Connectivity/]: java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9
> [08:42:46] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: OriginalPoster lost connection: Internal Exception: java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9

**Comment by Darkere** [comment] 2022-12-27 16:25
Please share the error message that gets printed when kicked.

**Comment by Klowes** [comment] 2022-12-28 13:46
@Darkere I've shared the logs for both the client and server regarding the boot

**Comment by hamurci** [comment] 2023-01-11 18:24
![211199997-66648d6a-bbd2-451b-a75f-d6aece0185de](https://user-images.githubusercontent.com/34452253/211887157-83f4eebc-7164-4a6e-b0de-5c987d19573a.png)
![211199962-697bd44e-3f04-4302-98fb-fc12e1065d5c](https://user-images.githubusercontent.com/34452253/211887179-3f70ebe6-2335-471d-b3e3-6ed9558da05e.png)
 I have same issue.and that is  the error message  when I click + icon. It only appears on create's mechanical crafter patterns

**Comment by aAndrew3030** [comment] 2023-02-06 18:01
The issue is happening with Fancy Trinkets also
https://github.com/McJtyMods/McJtyLib/issues/155

**Comment by aAndrew3030** [comment] 2023-02-06 18:03
https://github.com/McJtyMods/FancyTrinkets/issues/2

**Comment by chainlightning1** [comment] 2023-02-12 17:46
the same is happening to me at ATM 8

**Comment by davidgillen** [comment] 2023-05-07 12:05
Found same problem today in FTB Skies, again with recipes with > 9 components.

**Comment by raoulvdberge** [comment] 2023-11-05 16:41
Fixed by https://github.com/refinedmods/refinedstorage/pull/3588

**Closed as completed by raoulvdberge** 2023-11-05 16:41 UTC
Labels: bug

**Comment by raoulvdberge** [comment] 2023-11-12 13:23
This bug has been fixed in v1.12.4 for Minecraft 1.20.1 and v1.11.7 for Minecraft 1.19.2.
Thank you for reporting.

**Comment by raoulvdberge** [comment] 2023-11-26 12:23
Hello, this bug is now also fixed for Minecraft 1.18.2 in v1.10.6.
