### ISSUE TITLE
[Feature request] Don't re-sort items in grid until mouse cursor moves over a different item

### ISSUE THREAD

**Issue by lendrick** [refinedmods/refinedstorage#2032] opened 2018-10-13 15:24 UTC
Can you make it so when I'm clicking rapidly on an item in a grid, doesn't re-sort the grid until I move my mouse cursor to a different item?  If I'm trying to pick up several stacks of a single item, I usually end up picking up several different items because the stack sizes change and the items are sorted again as I'm clicking.

**Comment by Darkere** [comment] 2018-10-13 15:41
Duplicate of #2002

**Closed as completed** 2018-10-13 17:26 UTC
Labels: duplicate, enhancement
