### ISSUE TITLE
Odd textures for Crafting Grid and Controller

### ISSUE THREAD

**Issue by sofibabbles** [refinedmods/refinedstorage#2574] opened 2020-06-15 21:54 UTC
Issue description: Odd/messed up textures for Crafting Grid and Controller

What happens: The texture for the Crafting Grid and Controller seem to be something random. If I move the Crafting Grid, it changes back to normal. If I move the Controller, it will not change back to normal.
I have tried reloading textures/chunks as well as changing my resource pack back to the default. I've also tried leaving the server entirely.

Steps to reproduce:
Not sure. It just started happening out of no where.

Versions:
- Minecraft: 1.12.2
- Forge: 14.25.5.2854
- Refined Storage: 1.6.16

Does this issue occur on a server? Yes.

Visual (GIF): https://imgur.com/jYzBQSl

**Comment by tth05** [comment] 2020-06-15 23:18
What the...?

**Comment by Darkere** [comment] 2020-06-18 19:39
Duplicate of #2205

**Closed** 2020-06-18 19:56 UTC
