### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by z1043206827** [refinedmods/refinedstorage#3457] opened 2023-01-25 14:18 UTC
### Describe the bug

Random crashes occur in the game
https://paste.ubuntu.com/p/34Xyg2z39j/
[crash-2023-01-25_20.33.32-server.txt](https://github.com/refinedmods/refinedstorage/files/10500151/crash-2023-01-25_20.33.32-server.txt)

### How can we reproduce this bug or crash?

I can't reproduce this issue, it happens randomly

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.2

### What Refined Storage version is this happening on?

1.11.4

**Comment by raoulvdberge** [comment] 2023-01-25 14:26
Your bug report is a duplicate of another bug report that I can't be bothered to look up

**Closed as completed by raoulvdberge** 2023-01-25 14:26 UTC
Labels: bug

**Comment by Darkere** [comment] 2023-01-25 14:30
:D #3454
