### ISSUE TITLE
GL Error Spam

### ISSUE THREAD

**Issue by Rithenar** [refinedmods/refinedstorage#2714] opened 2020-10-20 01:57 UTC
#### Steps to reproduce:
1. Create a brand new world
2. Cheat in the necessary items for a basic RS system
3. Open Crafting Grid
4. See the sea of red in the console
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.3
- Forge: 34.1.23
- Refined Storage: 1.9.7

Does this issue occur on a server? [yes/no] both, SSP and MP

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://gist.github.com/Rithenar/1b007957c918365cf092a5fb294d8e98

**Comment by raoulvdberge** [comment] 2020-10-20 06:45
You see these errors with no items in your system?

**Comment by Rithenar** [comment] 2020-10-20 11:43
Yeah, with and without items

**Comment by raoulvdberge** [comment] 2020-10-20 12:20
Can you reproduce this with just RS installed and nothing else?

**Comment by Rithenar** [comment] 2020-10-20 12:25
Yes. I just run an instance with only RS and got this log https://gist.github.com/Rithenar/aeef2ab6951365308f696504ab8b88fb

**Comment by Rithenar** [comment] 2020-10-20 12:25
This is all I am using btw 
![image](https://user-images.githubusercontent.com/9939332/96585626-7793a280-12a5-11eb-998b-6864a6aaccdd.png)

**Comment by raoulvdberge** [comment] 2020-11-11 18:19
I cannot reproduce this. As GL errors are quite difficult debug as it can differ between computers and even graphics cards, I'm going to close this.

**Closed by raoulvdberge** 2020-11-11 18:19 UTC
