### ISSUE TITLE
Having to reconnect my external storage everytime i reload my game

### ISSUE THREAD

**Issue by LucienOliveira** [refinedmods/refinedstorage#2777] opened 2020-12-26 15:19 UTC
#### Steps to reproduce:
1. have a system hooked up to storage drawers with a external storage and drawer controller
2. fill it with items
3. reload the game
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: forge-35.1.13
- Refined Storage: 1.9.9

Does this issue occur on a server? [yes/no] not sure of

Some pictures

Reloaded the world:
![image](https://user-images.githubusercontent.com/44800538/103154084-91fe6680-4795-11eb-87c5-3feb31061e85.png)

After i broke a cable between RS controller and External storage:
![image](https://user-images.githubusercontent.com/44800538/103154152-10f39f00-4796-11eb-9c05-b0640077621b.png)

**Comment by embeddedt** [comment] 2020-12-26 16:00
Duplicate of #2636.

**Closed** 2020-12-26 16:09 UTC
