### ISSUE TITLE
Redstone detection not toggle-able

### ISSUE THREAD

**Issue by shadydeath** [refinedmods/refinedstorage#2957] opened 2021-05-05 10:43 UTC
#### Issue description:

Redstone detection button not working on Destructor (and all other stuff with this option: Importer, exporter, constructor)

#### What happens:

When i try to toggle the redstone detection state of the destructor it doesn''t toggle at all, the click of it responding is heard

#### What you expected to happen:

that the redstone state detection would toggle like it should

#### Steps to reproduce:
1. Let the server run for a while
2. Place destructor
3. Try to toggle the Redstone detection state
4. click button to see it not respond

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.2 ????
- Refined Storage: 1.9.12

Does this issue occur on a server? 

Yes

Gif showing the issue:
https://i.imgur.com/4mwHfsq.gif

**Comment by XenProject** [comment] 2021-05-08 21:16
Server error on click "Redstone Mode" button:

https://pastebin.com/FXCKky8U

**Comment by XenProject** [comment] 2021-05-08 22:06
I copied all files from hosting to local machine
Start dedicated server
Connect to localhost
And "Redstone Mode" button works perfectly

It's magic

**Comment by XenProject** [comment] 2021-05-09 08:49
@shadydeath, hi
I fix this problem by deleting all client side mods from server
+ delete InventorySorter (we used InvTweaksRenewed)

Deleted mods:
![AznthmxQSTFzAAAAAElFTkSuQmCC](https://user-images.githubusercontent.com/21991035/117565930-88c6c400-b0bc-11eb-81e6-d507e265f423.png)

+ CreativeCore, because it's dependency for AmbientSounds

**Comment by shadydeath** [comment] 2021-05-11 00:42
Ah okay gotta let the ATM6 devs know then since i use a pack made by them

**Comment by raoulvdberge** [comment] 2021-06-12 16:20
Duplicate of #2855

**Closed by raoulvdberge** 2021-06-12 16:20 UTC
