### ISSUE TITLE
[1.15.2] 1.8.5 Controller stopped functioning in specific location

### ISSUE THREAD

**Issue by UnfortunateName** [refinedmods/refinedstorage#2581] opened 2020-06-19 11:40 UTC
After a few hours the controller randomly stopped receiving power. Breaking and replacing the controller or connected power cables didn't fix the issue. However moving the controller to another location on the same system does allow it to regain power and run the storage system.

Currently using mekanism and flux networks for power.

**Comment by raoulvdberge** [comment] 2020-06-19 11:44
Any logs?

**Comment by UnfortunateName** [comment] 2020-06-19 11:56
Tried to pastebin latest just now but it exceeded their file size limit. Doing a quick search didn't find anything for refined storage in latest other than hours before this issue showed up. Is there other logs I should check? Didn't crash so nothing there.

**Comment by raoulvdberge** [comment] 2020-06-19 13:15
The debug log

**Comment by Darkere** [comment] 2020-06-19 13:17
Use https://gist.github.com/ for uploading the debug log file.

**Comment by UnfortunateName** [comment] 2020-06-19 13:23
> The debug log

Ah ok. Unfortunately I just logged off for the night after noticing it's 6am. I'll upload asap when I wake up tomorrow.

**Comment by UnfortunateName** [comment] 2020-06-20 03:06
Here's the debug log https://gist.github.com/UnfortunateName/d3ea32c4cf6c7ee7ddf4941dee27ab40

Also the specific block location that's causing it to fail is 229, 67, -4475

**Comment by Darkere** [comment] 2020-06-22 09:31
That looks like the system is running out of power or getting reset due to a redstone signal?

**Comment by UnfortunateName** [comment] 2020-06-22 10:46
It's on the exact same network for power where it shuts down and where I moved it to. Only things next to it are disk drive, crafting grid, and flux point or mekanism power cable. Not sure where it would be getting a redstone signal from.

**Comment by raoulvdberge** [comment] 2020-06-23 17:37
Unfortunately, the logs aren't really actionable. I'll have to close this as there are no reproduction steps for us to debug this.

**Closed by raoulvdberge** 2020-06-23 17:37 UTC
