### ISSUE TITLE
Dupe issue on crafters

### ISSUE THREAD

**Issue by Nico213** [refinedmods/refinedstorage#2979] opened 2021-05-16 16:21 UTC
I am able to dupe speed upgrades from refined storage in the crafters in conjunction with inventory sorter.

### What happens:
 when I have speed upgrades in a crafter and press middle mouse (assigned to sort inventory from inventory sorter mod) it puts 
 the speed upgrades in the first slot of the crafter while also leaving them in the upgrades slots, thus doubling the total amount 
 of speed upgrades, also when there is a pattern in the slot it is lost

### What you expected to happen:
 To leave the speed upgrades in their respective slots and to move around the patterns inside the crafter.

### Steps to reproduce:
1. place crafter with speed upgrades in it
2. press keybind for inventory sort (middle mouse) to sort the inventory
3. upgrades are now are being copied to the pattern slots

### Version:
- Minecraft: 1.16.5
- Forge: 36.1.4
- ftb direwolf 20 1.9.0
- Refined Storage: 1.9.12

### Does this issue occur on a server? 
 yes I am playing on a server, did not test if it also occurs on sp but I presume so.

### before sorting:
![image](https://user-images.githubusercontent.com/60398347/118404450-2b5de480-b673-11eb-8fb5-78412779d40f.png)

### after sorting:
![image](https://user-images.githubusercontent.com/60398347/118404458-39136a00-b673-11eb-845b-c2ef3cdef301.png)

**Comment by mars2325** [comment] 2021-05-18 18:45
Nice! I just found this out and was about to report it and saw you post. Hope developers can see this

**Comment by Darkere** [comment] 2021-05-19 20:16
Duplicate of #2833

**Closed by Darkere** 2021-05-19 20:16 UTC
