### ISSUE TITLE
Can't give or take items to RS. When Immersive Engineering Fluid Tank is connected as External Storage

### ISSUE THREAD

**Issue by archer9234** [refinedmods/refinedstorage#2631] opened 2020-07-25 15:15 UTC
#### Issue description:
Unable to remove or put items into RS.

#### What happens:
When attaching external fluid storage to Immersive Engineering's Tank. Attempting to take items in/out of the grid. Either from other external sources or RS storage, fails. 

#### What you expected to happen:
Fluid Grid connected to Immersive Engineering doesn't block interaction with RS.

#### Steps to reproduce:
1. Make IE Fluid Tank. Not sure if it's all fluid's. But use Creo oil
2. Connect External Storage to tank.
3. Attempt to add or take items out of any connected storage to RS, will not work. Grid items will also remain visible when fully disconnected from the entire system.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.1
- Forge: 32.0.69
- Refined Storage: 1.9.2

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Edivad99** [comment] 2020-08-20 15:21
I think it is the same problem reported here #2568

**Comment by Darkere** [comment] 2021-01-31 15:35
Duplicate of #2568

**Closed by Darkere** 2021-01-31 15:35 UTC

**Comment by amohacker** [comment] 2021-07-14 01:52
I also have this bug in 1.16.5 specifically when i have an immersive engineering fluid barrel attached to the system i become unable to take items out of the system after i put an item into the system.
The other fluid containers seem to work fine it's just the barrel as far as i can tell
