### ISSUE TITLE
External storage have to be reset every login, if it is set to work on high redstone

### ISSUE THREAD

**Issue by pwaksman973** [refinedmods/refinedstorage#2918] opened 2021-03-19 03:54 UTC
#### Issue description:
When you have an external storage, and config it to only work with High Signal from a redstone, when you first load the world, even if it have a redstone power, it will not work, so you have to disable and enable back the redstone.

#### What you expected to happen:
When you load the world, for it to "remember" it stat or check near by blocks for redstone.

#### Steps to reproduce:
1. Get a draw controller anywhere, with some draws and itens on it.
2. Attach a external storage at the botton. Config it to only work when it receive a redstone signal.
3. At the left or right of the external storage, add a redstone torch, not to the ground, to the side of the block near it, so it like as a inverter when the block gets redstone power.
4. On top of the block that you have attached the redstone torch, place a leaver. With that the external storage should be always on unless you turn the leaver on, which will disable the external storage.
5. Leave the leaver off, and exit the world, load back the world and check the refined storage grid for the itens. They won't be avaliable. Flip the leaver on/off again, now the itens are avaliable.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: forge-36.0.45
- Refined Storage: refinedstorage-1.9.12

Print of the setup.

![setup](https://user-images.githubusercontent.com/78715804/111729324-8e86f280-884d-11eb-9f71-942ab639e8d6.png)

**Comment by dixonw2** [comment] 2021-03-21 15:28
Have same issue except that the Redstone steps aren't necessary. Every time my server restarts I have to break/replace the external storage block.

**Comment by Darkere** [comment] 2021-03-21 15:36
duplicate of #2636

**Closed by Darkere** 2021-03-21 15:36 UTC
