### ISSUE TITLE
Exporting Fluids from an Ender Tank (Ender Tanks Mod) makes it impossible to withdraw items from any Grid

### ISSUE THREAD

**Issue by BrainInBlack** [refinedmods/refinedstorage#3237] opened 2022-02-01 22:27 UTC
### Describe the bug

As the title says, exporting fluids from an Ender Tank, attached via External Storage, makes it impossible to withdraw items from any Grid and newly added items will no longer "stack" in the GUI. Using a "normal" tank, in my case a tank from Mekanism, as a proxy works just fine, it is save to assume that this is an issue with the interaction between the Ender Tanks mod and RS.

### How can we reproduce this bug or crash?

1. Have both RS and Ender Tanks installed
2. Attach a filled Ender Tank to the network via External Storage
3. Export the stored liquid.
4. Try to remove items from the network via the grid, or automatically add new items to the network to see that items no longer "stack"
5. Profit?

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.23

### What Refined Storage version is this happening on?

1.9.17

### Relevant log output

```shell
N/A
```

**Comment by Darkere** [comment] 2022-02-01 22:42
Duplicate of #2568

**Closed by Darkere** 2022-02-01 22:42 UTC
Labels: bug
