### ISSUE TITLE
Relay does not appear to be working

### ISSUE THREAD

**Issue by Pontiac76** [refinedmods/refinedstorage#3198] opened 2021-12-30 04:05 UTC
### Describe the bug

I'm playing OceanBlock for 1.16.  OB is 1.10.

I noticed for the first time a couple days ago that RS had a Relay.  Apparently, depending on the status of the received redstone signal, the relay should be "on" or "off" allowing data to be put through or not.

I have a bunch of constructors and destructors sitting in series with each type  Y'd out to different lines.  The constructors always have access to the  controller, while the destructors are put behind the relay.  The constructors and destructors do not talk directly with the relay in place.

I couldn't seem to get the relay to turn ON.  I set the rely to ignore the redstone state, and it's not allowing the deconstructors to do their job.  If I remove the relay and put in a normal cable, the deconstructors do the job just fine.

I've put a detector next to the relay, and the detector is always connected to the controller.  I've toggled the detector on and off through various means, but the relay just will not allow the traffic to go through.

There is no coloring going on with the relay either.  It's freshly autocrafted.

### How can we reproduce this bug or crash?

Validate Functionality without relays:
From the controller (With appropriate storage on the network), wire out to a constructor.  Have the constructor place something.
Somewhere on the line, branch out and place a destructor to remove whatever the constructor is placing into the world.
The block should be broken and placed pretty quickly.

Break the line just before the destructor and put in a relay.
Put a detector right next to the relay.
Wire the detector back to the main line if not already connected.
Set the detector to be on or off through whatever means needed.

The relay does not pick up any signal from the detector, no matter its status, and the relay does not turn on.

IE:

```
CONTROLLER --- ----- ------ ----- ----- ----- ----- CONSTRUCTOR
(With Storage)       \                                 [BLOCK]
                      ----- DETECTOR ---- RELAY ---- DESTRUCTOR


```

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.19

### What Refined Storage version is this happening on?

1.9.16

**Comment by Darkere** [comment] 2021-12-30 13:41
Duplicate of #3138

**Closed by Darkere** 2021-12-30 13:41 UTC
Labels: bug

**Comment by mcbigboy** [comment] 2022-01-06 15:14
I'm playing  Chroma Technology 2, I put down the relay and in other version the relay would be on. In this version the block is off and will not change. I put a level on it and it would not change i'ts allway off.

**Comment by Pontiac76** [comment] 2022-01-09 02:47
What version of RS is installed on Chroma Tech 2?
