### ISSUE TITLE
Changing the amount of fluid a processing recipe produces does not work

### ISSUE THREAD

**Issue by pnieuwkamp** [refinedmods/refinedstorage#2872] opened 2021-02-07 16:46 UTC
#### Issue description:
Using the pattern grid, I can't change the amount of fluid a processing recipe produces. It does work on the input side of the recipe.

#### What happens:
When trying to change the amount I get the GUI that lets me change the number, but after clicking "Set" the number stays at "1 B" instead of the amount I tried to set it to. Programming a pattern confirms that this is not just a visual bug, as the pattern also shows "1 B Water"

#### What you expected to happen:
I expect the pattern grid to allow me to change the amount

#### Steps to reproduce:
1. Open pattern grid
2. Set the recipe mode to "Processing"
3. Set the the recipe type to fluid 
3. Use a bucket to add a fluid to the output 3x3
4. Click the fluid
5. Change the number from 1000 into something else
6. Click "Set"

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.15
- Refined Storage: 1.9.11
(also happens with 1.16.4/35.1.37/1.9.11)

Does this issue occur on a server?
I'm in a singleplayer world, haven't tested on a server

**Comment by Darkere** [comment] 2021-02-07 17:16
Duplicate of #2822

Thanks for the report anyways.

**Closed by Darkere** 2021-02-07 17:16 UTC
