### ISSUE TITLE
[Duping Issue] Weird interaction with "Inventory Sorter"mod

### ISSUE THREAD

**Issue by RedHelios7035** [refinedmods/refinedstorage#3042] opened 2021-07-18 01:03 UTC
#### Steps to reproduce:
1. Place a crafter, insert n # of speed upgrades
2. Use the "sort inventory" function of "inventory sorter" mod in the pattern space.
3. Inside the first slot of the crafter, n # of speed upgrades will be duped. If there are any patterns present in that slot, that item will be deleted.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.16
- Refined Storage: 1.9.12

Does this issue occur on a server? (unclear)

**Comment by Darkere** [comment] 2021-07-25 10:06
Duplicate of #2833

**Closed by Darkere** 2021-07-25 10:06 UTC
