### ISSUE TITLE
Bug DUPE with mod

### ISSUE THREAD

**Issue by DarkShyMW** [refinedmods/refinedstorage#2961] opened 2021-05-08 19:23 UTC
#### Issue description:
Sometimes user try to take resourse, but he cant.
#### What happens:
https://disk.yandex.by/i/1xSp9EjF_oPPGg

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.2
- Refined Storage: refinedstorage-1.9.12

Does this issue occur on a server? [yes/no]
yes 

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

https://disk.yandex.by/i/1xSp9EjF_oPPGg

**Comment by MrStatman80** [comment] 2021-05-10 11:01
But did you delete all the items you duped before the fix?

No so you're a cheater  lol

Joking but delete all thou

**Comment by Darkere** [comment] 2021-05-19 20:16
Duplicate of #2833

**Closed by Darkere** 2021-05-19 20:16 UTC
