### ISSUE TITLE
NullPointerException during loading

### ISSUE THREAD

**Issue by YarinQuapi** [refinedmods/refinedstorage#3162] opened 2021-12-04 21:21 UTC
#### Issue description:
Crash during game loading

#### What happens:
The game does not load with the mod present

#### What you expected to happen:
The game loaded

#### Steps to reproduce:
1. Initialize the game. Boom.

#### Version (make sure you are on the latest version before reporting):
- Minecraft: 1.16.5
- Forge: 36.2.9 / 36.2.19 (Tested on both versions)
- Refined Storage: 1.9.16

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/gtPD31t4

**Comment by Darkere** [comment] 2021-12-04 21:39
Duplicate of #3129

**Closed by Darkere** 2021-12-04 21:39 UTC
