### ISSUE TITLE
Issue with removing items from the rs system

### ISSUE THREAD

**Issue by coldfire80** [refinedmods/refinedstorage#3325] opened 2022-06-25 14:25 UTC
### Describe the bug

UsingDirewolf20 1.18 v1.6.1- Bug with refined storage and ender tanks. When an external storage is placed on an ender tank items can not be pulled from a grid on that system. I have two systems and tried it on both with the same result. This is in a single player world. Not sure if the issue is on your end or ender tanks.

### How can we reproduce this bug or crash?

Place external storage on ender tank
try to pull items from the system

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

unsure

### What Refined Storage version is this happening on?

1.10.2

**Comment by AerosAtar** [comment] 2022-07-06 01:32
I am having a similar issue (cannot remove any items from a grid), but instead of an Ender Tank, it is with a multiblock fluid storage (in my case the Fluid Tank from Immersive Engineering, though I suspect it would have the same issue with other multiblock storage).

Minecraft 1.16.5, Forge 36.2.35, Refined Storage 1.9.18.

**Comment by raoulvdberge** [comment] 2022-12-05 19:16
Duplicate of #2568

**Closed as not planned by raoulvdberge** 2022-12-05 19:16 UTC
Labels: bug
