### ISSUE TITLE
Autocraft is not working

### ISSUE THREAD

**Issue by Looopering** [refinedmods/refinedstorage#2630] opened 2020-07-19 20:37 UTC
Issue description: autocraft does not work
What happens: autocraft does not work with chargeable items, for example, Energy Cubes from Mekanism
What you expected to happen: autocraft works with chargeable items
Steps to reproduce:
Build Autocrafting system.
Make a pattern describing recipe of an Induction Provider Basic
Begin craft.
Version (Make sure you are on the latest version before reporting):
Minecraft: 1.12.2
Forge: 1.12.2-14.23.5.2854
Refined Storage: 1.6.16
Does this issue occur on a server? [yes/no] yes

If a (crash)log is relevant for this issue, link it here:
[pastebin/gist/etc link here]

https://cloud.githubusercontent.com/assets/22776271/19283640/5bc47826-8ffb-11e6-9952-0882a44a66d2.png

https://cloud.githubusercontent.com/assets/22776271/19283669/747178c4-8ffb-11e6-8265-2ae70aaaac36.png

**Comment by Darkere** [comment] 2020-07-19 20:42
Duplicate of https://github.com/refinedmods/refinedstorage/issues/1990

**Comment by Looopering** [comment] 2020-07-19 20:42
Yeah obviously because it isn't fixed yet

**Comment by Darkere** [comment] 2020-07-19 20:51
The fix is in that issue. It is not an issue we can do anything about.

**Comment by Looopering** [comment] 2020-07-19 20:58
What do you mean by "The fix is in that issue?"

**Comment by Darkere** [comment] 2020-07-19 21:00
#1990 <--- Click the link. If you don't want to read I even made a video that shows how to work around the problem (posted near the end).

**Closed** 2020-07-19 21:13 UTC

**Comment by Looopering** [comment] 2020-07-19 21:20
Thanks you can close this issue

**Comment by Looopering** [comment] 2020-07-19 21:20
Thanks it works now
