### ISSUE TITLE
block dupe

### ISSUE THREAD

**Issue by AndromeHyperion** [refinedmods/refinedstorage#2643] opened 2020-08-01 11:36 UTC
#### Issue description:
block duplication bug with constructor & destructor.
#### What happens:
It places the diamond ore but doesn't consume it in the RS system
#### What you expected to happen:
that the amount of diamond ore decreases and the amount of diamond increases. the last part happens.
#### Steps to reproduce:
1. make RS system with storage
2. place a constructor and destructor and connect it with the RS system
3. fill the destructor with 1 fortune 3 upgrade, 3 speed upgrades and fill the constructor with 4 speed upgrades (Might not be needed)
4. add the block you want to place in the constructor, tried this with diamond ore and a block from the mod Powah

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16.1
- Forge: 32.0.98
- Refined Storage: 1.9.2

Tested this in All the mods 6 and enigmatica 6 but also with just Forge, Refined storage, Refined Storage addons and Powah to power the system

Does this issue occur on a server? [no]

**Comment by Darkere** [comment] 2020-08-01 11:38
Duplicate of #2641

**Closed** 2020-08-01 13:18 UTC
