### ISSUE TITLE
[1.16.3] Please set experimentalForgeLightPipelineEnabled to true even though it is already set

### ISSUE THREAD

**Issue by raziel23x** [refinedmods/refinedstorage#2727] opened 2020-10-30 01:36 UTC
#### What happens:
![image](https://user-images.githubusercontent.com/441966/97649326-6d07a480-1a2d-11eb-9e89-c41da58fca75.png)
![image](https://user-images.githubusercontent.com/441966/97649707-5e6dbd00-1a2e-11eb-95f7-6b9bb79d5eb2.png)

#### What you expected to happen:
the message to not be present since already set try in the config file already

#### Steps to reproduce:
 just load the mod with forge 34.1.35 does not occur with 34.1.25 and below

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.3
- Forge: 34.1.35
- Refined Storage: refinedstorage-1.9.8.jar

Does this issue occur on a server? [yes/no]
not sure

**Comment by embeddedt** [comment] 2020-11-09 19:53
I can confirm the same behavior with Forge 34.1.42 (same versions of everything else).

**Comment by raoulvdberge** [comment] 2020-11-11 18:16
I can not reproduce this. Please ensure that you have restarted MC.

**Comment by embeddedt** [comment] 2020-11-11 18:20
@raoulvdberge This still happens even after Minecraft is restarted multiple times; I have confirmed that the setting is set to `true` in `config/forge-client.toml`.

**Comment by raoulvdberge** [comment] 2020-11-11 18:21
Are you sure that you've changed the correct option and *then* restarted? There are 2 lighting pipeline related configs.

**Comment by embeddedt** [comment] 2020-11-11 18:22
```
	#EXPERIMENTAL: Enable the Forge block rendering pipeline - fixes the lighting of custom models.
	experimentalForgeLightPipelineEnabled = true
	#Enable the Forge block rendering pipeline - fixes the lighting of custom models.
	forgeLightPipelineEnabled = true
```

I copied these from my Forge config. They are the correct settings, right?

**Comment by raoulvdberge** [comment] 2020-11-11 18:25
That should work, yeah. Not sure what to do now as I can't reproduce it.

Did you try with just RS installed?

**Comment by embeddedt** [comment] 2020-11-11 18:34
Thanks for that suggestion. I realized that I had included OptiFine in this modpack since I was trying to compensate for post-1.12 rendering performance loss. When OptiFine is included the message appears regardless of the Forge setting. I don't recall seeing a problem with RS blocks rendering though.

**Comment by raoulvdberge** [comment] 2020-11-11 18:42
The experimental lighting pipeline is not compatible with Optifine, so I imagine Optifine is dynamically disabling it. Thanks for confirming that it's an Optifine issue though!

(Try placing a disk drive encased with dirt, the disk drive will be very dark)

**Comment by embeddedt** [comment] 2020-11-11 18:55
Wow; the old lighting pipeline really is buggy. Is there a way to detect if OptiFine is present, and if so, print a warning message to the chat that Refined Storage is not compatible with OptiFine?

**Comment by raoulvdberge** [comment] 2020-11-11 19:01
Not compatible is rather strong wording, I think I can change the nagging message a bit.

**Comment by Bellwar** [comment] 2020-12-25 22:27
Do you think there can be a solution to this issue? I'm not as deep into it, but I have CLL Log triggering a lot about disk drive (don't have any cables or anything more complex yet). I don't really care about that, but will it mess with more blocks? I have OptiFine since I have 1440p display and to be honest, I can't play on any vanilla Gui setting and it really helps with performance at the same time. So I would really like to keep it.

**Comment by raoulvdberge** [comment] 2020-12-25 23:24
I tried detecting optifine at runtime but it didn't really work.

**Comment by Darkere** [comment] 2020-12-25 23:26
This is what Jared does to detect it.
https://github.com/jaredlll08/TipTheScales/blob/25ded3a4fb085aa04d669ee8c98f25a5ec24580c/src/main/java/com/blamejared/tipthescales/TipTheScales.java#L30

**Comment by embeddedt** [comment] 2020-12-26 00:06
I'm not really familiar with the modding scene - what are the chances of getting OptiFine to fix this lighting issue on their end?

**Comment by raoulvdberge** [comment] 2020-12-26 06:32
Less than zero

**Comment by Bellwar** [comment] 2020-12-26 09:02
Yes I know optifine wont do a thing about it. It's more of can someone else do but I understand if not. Also, could there be an option in optifine that if you turn it off it won't mess with it?

**Comment by embeddedt** [comment] 2020-12-26 14:07
Probably not, since from what I've read OptiFine seems to be a very invasive mod. I suspect that it has to replace the lighting pipeline to be able to optimize things. Maybe, when the experimental pipeline is no longer experimental, OptiFine will finally add support for it.

**Comment by raoulvdberge** [comment] 2020-12-26 15:40
Yes, Optifine replaces the entire lighting pipeline, without an option of disabling that functionality IIRC. So, that also means they can't support the experimental one.  Not much that I can do about that on my end unfortunately.

**Comment by embeddedt** [comment] 2020-12-26 15:43
I wonder if the disk drive is the only RS block which gets affected by this, because of the 3D drives feature. Perhaps it would be possible to fall back to 2D drive rendering if OptiFine is detected? Or does this affect other blocks as well?

**Comment by lolgootem** [comment] 2021-01-21 02:17
How do you access the config and what is the fix for the lighting issue every time I play now I lag a ton so I was hoping to fix it but I can't even get in this config.

**Comment by embeddedt** [comment] 2021-01-21 03:01
The config is in `.minecraft/config/forge-client.toml`. The setting to change is `experimentalForgeLightPipelineEnabled` and it needs to be made `true`.

**Comment by lolgootem** [comment] 2021-01-21 04:53
Thanks a ton

**Comment by SilencerDude** [comment] 2021-01-23 01:20
Is this a game breaking issue or will it just cause lighting issues with blocks?

**Comment by embeddedt** [comment] 2021-01-23 01:21
From what I can tell, it has no impact on gameplay besides the strange rendering.

**Comment by Brittank88** [comment] 2021-01-23 02:03
Could we at least have a config option in RS to disable the chat warning entirely (of course, defaulting to showing the warning)? It's a little annoying to see the naggy message every time you enter a world.

**Comment by Brittank88** [comment] 2021-01-29 11:14
Any update on this?

Furthermore, LatvianModder said the current check won't even work on a dedicated server regardless of anything else (we were discussing it in his server):
![image](https://user-images.githubusercontent.com/24266948/106268458-41d85f80-627f-11eb-84e0-549d66f62de1.png)

**Comment by Maevarienn** [comment] 2021-02-06 05:55
Yeah, would love to see a dedicated config option to disable to the log output or something. Just for server managers at least. Having the same "issue" as above.

**Comment by miiichael** [comment] 2021-03-06 06:51
Likely relevant: https://github.com/sp614x/optifine/issues/4171 (basically confirmation of WONTFIX from sp614x's end)

I don't know how unreasonable it is to require mod authors to not rely on experimental (and barely documented) Forge features...

FWIW some lighting weirdness can be mitigated by turning off Smooth Lighting (but of course this makes the lighting super unsmooth :P)

**Comment by Brittank88** [comment] 2021-03-07 12:24
I mean, at the very least can we just turn off the warning? I know I've already personally requested this but it's a rather small feature to add and it's kinda silly that currently our hand is forced here.

**Comment by jacket430** [comment] 2021-05-18 09:02
I do find it a bit ironic optifine/shaders aren't supported considering they're in almost all of the screenshots on the mods page haha

**Comment by embeddedt** [comment] 2021-05-18 12:55
I believe the screenshots are from 1.12 or earlier but I could be wrong.

**Comment by LeftofZen** [comment] 2021-06-01 07:31
This is quite ridiculous, just provide a config option in refined storage to render the block without its fancy animated texture. I'm in a modpack in excess of 200 mods and these refined storage blocks are the only ones with rendering issues. Whilst it may be optifine's fault, every other mod can deal with it except refined storage, which is kind of hilarious.

**Comment by Brittank88** [comment] 2021-06-01 10:21
To be fair to the RS devs, they may have opted for some process a long time ago that would now require a time-consuming rewrite to be compatible with Optifine.

What is not understandable is why they won't let us disable this textual warning, at our own risk. It seems illogical.

**Comment by raoulvdberge** [comment] 2021-06-01 10:25
I'm going to remove this warning for the next version, as it causes more problems than it's worth.

**Closed** 2021-06-12 15:27 UTC
Labels: Bug
