### ISSUE TITLE
[1.7.3] Grid shows empty incorrectly

### ISSUE THREAD

**Issue by settop** [refinedmods/refinedstorage#2554] opened 2020-06-05 18:27 UTC
#### Issue description:
The crafting grid was showing empty despite having several full drives, external storage and auto crafting setup. This was only a gui glitch since everything else was working fine and JEI could pull items out when auto completing a craft.
By exporting everything out of the affected drive, I found it was due to the item "Capsule Pendant" from the mod "Potion Capsule"

#### What happens:
Crafting crid shows nothing is in the network.

#### What you expected to happen:
I expected to see all my items and auto crafting

#### Steps to reproduce:
1. Add the "Capsule Pendant" to a refined storage system, either in a drive or external storage
2. Observe crafting grid is empty

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.14.4
- Forge: 28.1.61
- Refined Storage: 1.7.3
 - PotionCapsule: 1.1.1

Does this issue occur on a server? [yes/no]
Don't know, only tested in a single player world

**Comment by Darkere** [comment] 2020-06-05 18:49
Duplicate of #2362

Update Potion Capsule mod.

**Closed** 2020-06-07 10:21 UTC
