### ISSUE TITLE
Game crash when importing fluids

### ISSUE THREAD

**Issue by MrStatman80** [refinedmods/refinedstorage#2966] opened 2021-05-10 10:55 UTC
My game crashes when I use an importer and select fluid into go into an external storage for fluids.
And Yes both are on for fluids

But when I leave the area my game crashes

1. Try importing fluids
2. use external storage on a tank
3. leave the area

For the mod pack i am using it with is All The Mods 6: To The Sky

- Refined Storage: 1.9.12

This is only on my client as i don't on a server

and crashlog is

https://pastebin.com/Xp3RLEQp

**Comment by orangelynx** [comment] 2021-05-13 08:17
Duplicate of #2744

**Closed** 2021-05-13 08:27 UTC
