### ISSUE TITLE
Cannot get items from grid

### ISSUE THREAD

**Issue by sadovsf** [refinedmods/refinedstorage#2875] opened 2021-02-10 08:53 UTC
#### Issue description:
Lately (i believe it did not started with some particular update or something but rather with grid growing) i have often issues with crafting grid not giving me items. I can see them but when i try to obtain them it it almost seems like input is ignored. I have to reopen crafting grid or wireless crafting grid. Search again and then it usually works until it breaks again after several searches and gets. Another manifestation of i believe same issue is that some time same items get duplicated icons. For example when i place iron ingots in grid i can see them 2x one amount it that i placed inside, other is what was already in. They also "remerge" when i reopen interface. There is no crafting running in background when iam observing these issues.

If it would help i can probably upload and send you link to world download.

#### What you expected to happen:
Grid should work consistently and if it claims that there are items i should be able to obtain them.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.14
- Refined Storage: refinedstorage-1.9.11.jar, refinedstorageaddons-0.7.2.jar
- Over all using latest Direwolf20 1.16 v1.6.1 mod pack by Feet the Beast

Does this issue occur on a server? yes

**Comment by Darkere** [comment] 2021-02-10 08:58
There is currently an issue where this can happen with some inventories that are connected via external storage. Try disabling them.

**Comment by sadovsf** [comment] 2021-02-10 09:32
iam using external storage only for some really big counts like stone or fluids. This happens quite consistently with items that are stored on drives. Just minute ago i searched for redstone, took dust but was not able to take torch right after that. I had to reopen grid. Search again and then it worked

**Comment by Darkere** [comment] 2021-02-10 09:49
The issue is that if the inventory/block connected via external storage updates you are no longer able to extract ANY items from the grid.

**Comment by sadovsf** [comment] 2021-02-10 09:54
aaaah i see now. And as iam mining and storing stones and stuff in external storage then essentially every time something runs around i get locked out. Although it will be hard to make some workaround when i think about it. Do you have some even rough idea when this could be fixed? (I work as full time c++ prog so iam aware that its hard to estimate) Or maybe could you give me some more info about what causes these updates? Does it lock item grid same way when external fluid tank changes its content?

**Comment by Darkere** [comment] 2021-02-10 09:58
The exact issue appears when the connected block sends a blockupdate... As such it depends entirely on the block when and how often the issue appears. 

Some blocks might send a blockupdate if the inventory changes, some others when you interact with it and then there's the enderchest that sends one every second.

As for a fix, I've proposed a fix here #2789 but I don't think Raoul has had the time to look at this quite yet.

**Comment by sadovsf** [comment] 2021-02-10 10:05
Ok i think i know exactly what is causing it then based on when it started to happen. In my case it is probably Tank from Mekanism i have hooked up as external storage. OK in mean time i will try to find a way how to get around it (iam not storing it in system by import so i can limit amount and not overfill storage with liquid i need few buckets only

**Comment by Darkere** [comment] 2021-02-10 10:27
Alright if that was the issue I'm closing this one as it's a duplicate of #2568

**Closed by Darkere** 2021-02-10 10:27 UTC

**Comment by sadovsf** [comment] 2021-02-10 10:29
Sure, i will test it today to validate. But it is most likely same case

**Comment by sadovsf** [comment] 2021-02-18 10:41
I can confirm that after removing some tanks and changing use many cases from external storage to importers with redstone detectors to limit amount it works well

**Comment by zackattac11** [comment] 2022-04-03 04:24
Just a note from my experiences, I have found that when this bug occurs, stacking bugs out within refined storage as well. It seems that when using JEI to force items from storage into the crafting grid, it separates the stacks into multiple stacks with divisions of 8. I.e. stacks that contain 64, 32, 16, and then 8 of an item. Perhaps this is a memory bug rather than what I have seen said as a problem with the neighbors-changed function?

This is coming from one who rarely uses external storage other than a simple drawer in which to hold and compress
