### ISSUE TITLE
Crash upon right clicking Controller

### ISSUE THREAD

**Issue by Eternaldark0** [refinedmods/refinedstorage#2689] opened 2020-10-01 17:44 UTC
#### Steps to reproduce:
1. Tried multiple times, Right clicking would crash every time.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):   refinedstorage-1.9.6

- Minecraft: 1.16.3
- Forge: forge-1.16.3-geckolib-2.1.1
- Refined Storage: refinedstorage-1.9.6

Does this issue occur on a server? [yes/no]  no

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]   https://pastebin.com/F6T7rY52

**Comment by Darkere** [comment] 2020-10-01 17:47
Duplicate of #2687

**Closed** 2020-10-01 19:49 UTC
