### ISSUE TITLE
Items invisible to one player, others can still see them

### ISSUE THREAD

**Issue by asoftbird** [refinedmods/refinedstorage#2279] opened 2019-07-11 22:55 UTC
Edit: I am aware this is a duplicate of #2274, but "Restarting and/or deleting playerdata usually fixes this." is not a solution but a workaround. Deleting playerdata gets annoying as progress from other mods is lost, and the server admin isn't always online to fix this. 

#### Issue description:
At random intervals, the RefinedStorage system stops showing items in grids. Items can still be deposited into the system, but no longer taken out of it, since none are shown. The disks show items taking up storage.
Other players can still see the items in the affected system, while the player with the issue can see no items in none of the storage systems, not even in those of other players.

Setup: Controller, drive with 4 4k disks, Crafting grid. 
Drive storage is about 50% used. Plenty of power, no redstone activity in the vicinity.

Rebuilding the entire system, toggling redstone and power, or replacing drives doesn't help. Building a new system and putting items in that does not work either. 
Relogging does not help.
So far the only fix I've been able to find is rebooting both the client and the server, doing just either on it's own does not help.
The error log shows no errors, no events, nothing.

I have not been able to reproduce this issue, though it has happened multiple times in a timespan of about four days. 

#### Versions:
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.14
- RefinedStorage Addons: 0.4.4

Does this issue occur on a server? yes

**Comment by allanf181** [comment] 2019-07-16 17:03
Same here

refinedstorage-1.6.14
refinedstorageaddons-0.4.4
Forge Mod Loader version 14.23.5.2838 for Minecraft 1.12.2

this started after I opened a system with some black hole unit, my game crashed for a few minutes but the system opened normally, after that I could not see any item in any system.

restarting the server did not solve

**Comment by Darkere** [comment] 2019-07-21 14:55
Had another player on reddit. Restarting his SP game did not fix it but restarting the entire PC did. 

https://www.reddit.com/r/feedthebeast/comments/cfano5/refined_storage_items_not_showing_up/

**Comment by HixxyDubz** [comment] 2019-08-23 19:34
just experienced this today on my private server, playing All The Mods 3 Remix 1.12.2

**Comment by Darkere** [comment] 2019-10-14 09:08
Some update on the Issue:

The last 7 Instances of this that have come to my attention have all been fixed by restarting the client. 

There is a way to temporary reproduce this bug. It can be achieved by using an auto-clicker to very quickly open a grid. Closing the grid and reopening fixes it in this case. May or may not be related to the permanent issue in some way.

**Comment by artheus** [comment] 2019-10-25 09:53
Same here. Whenever I try to open the crafting grid when this is happening. I get this exception in the logs ```[11:01:25] [Client thread/ERROR] [jei]: Error caught from Recipe Category: cofh.thermalexpansion.plugins.jei.machine.pulverizer.PulverizerRecipeCategoryPetrotheum
java.lang.ClassCastException: com.raoulvdberge.refinedstorage.integration.jei.RecipeWrapperCover cannot be cast to cofh.thermalexpansion.plugins.jei.machine.pulverizer.PulverizerRecipeWrapper
        at cofh.thermalexpansion.plugins.jei.machine.pulverizer.PulverizerRecipeCategoryPetrotheum.setRecipe(PulverizerRecipeCategoryPetrotheum.java:25) ~[PulverizerRecipeCategoryPetrotheum.class:?]
        at mezz.jei.gui.recipes.RecipeLayout.create(RecipeLayout.java:69) [RecipeLayout.class:?]
        at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:198) [RecipeGuiLogic.class:?]
        at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:492) [RecipesGui.class:?]
        at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:538) [RecipesGui.class:?]
        at mezz.jei.gui.recipes.RecipeGuiLogic.setRecipeCategory(RecipeGuiLogic.java:231) [RecipeGuiLogic.class:?]
        at mezz.jei.gui.recipes.RecipeCategoryTab.handleMouseClicked(RecipeCategoryTab.java:33) [RecipeCategoryTab.class:?]
        at mezz.jei.gui.recipes.RecipeGuiTabs.handleMouseClicked(RecipeGuiTabs.java:133) [RecipeGuiTabs.class:?]
        at mezz.jei.gui.recipes.RecipesGui.mouseClicked(RecipesGui.java:327) [RecipesGui.class:?]
        at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533) [blk.class:?]
        at mezz.jei.gui.recipes.RecipesGui.handleMouseInput(RecipesGui.java:304) [RecipesGui.class:?]
        at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501) [blk.class:?]
        at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759) [bib.class:?]
        at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) [bib.class:?]
        at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]```
Hope this will be helpful for the devs.

**Comment by raoulvdberge** [comment] 2019-10-25 10:55
@artheus This is another issue. Please create a new issue.

**Comment by Darkere** [comment] 2019-10-25 11:07
its a duplicate of https://github.com/raoulvdberge/refinedstorage/issues/2215

Not sure if

**Comment by juliand665** [comment] 2020-02-27 18:56
Just had this issue too in Ultimate Alchemy, just started happening out of nowhere. Reopening the world or creating a new one didn't help, but restarting the client fixed it

**Comment by RundownRhino** [comment] 2020-04-08 12:34
This issue is still present on MC 1.12.2, RS 1.6.15, RSAddons 0.4.4. Singleplayer world, absolutely no indications something is wrong except not being able to see any items. Reloading the world doesn't help. Restarting the client entirely does.

Unlike mentioned earlier in the thread, there were no exceptions in logs at the time of the problem's appearance.

**Comment by votex09** [comment] 2020-06-17 05:05
Same problem here.  A user on my server could not see his items, but I could. 1.6.16 - 1.12.2

**Comment by raoulvdberge** [comment] 2020-10-16 17:31
Closing as 1.12 is no longer maintained and we were never really able to reproduce this consistently to find a fix for this.

**Closed by raoulvdberge** 2020-10-16 17:31 UTC
Labels: Bug, MC 1.12
