### ISSUE TITLE
External storage panel to double any item

### ISSUE THREAD

**Issue by StarZeroRI** [refinedmods/refinedstorage#3255] opened 2022-03-08 11:59 UTC
### Describe the bug

When the same container is read repeatedly from the external storage panel, the number of contents displayed is multiplied. Items that are multiplied can participate in crafting when manually crafting in the RS crafting terminal. 

### How can we reproduce this bug or crash?

Example: 6 external storage panels are placed against the same box. There is 1 diamond block in the chest. At this point, there are 6 diamond blocks displayed in the synthesis terminal. When the player manually takes another diamond block to synthesize and split it into diamonds. It will synthesize 6*9=54 diamonds at one time. 

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.2.6

### What Refined Storage version is this happening on?

refinedstorage-1.9.17

### Relevant log output

```shell
air
```

**Comment by Darkere** [comment] 2022-03-08 12:09
Duplicate of #3242

**Closed by Darkere** 2022-03-08 12:09 UTC
Labels: bug
