### ISSUE TITLE
Game crashes when applying dye to detector

### ISSUE THREAD

**Issue by NitroSvennen** [refinedmods/refinedstorage#2998] opened 2021-06-04 10:35 UTC
#### Issue description: 
Game crashes when trying to apply dye to a detector.

#### What happens: 
When applying a dye to the detector from RS the game shuts down (saving world and then shuts down the instance).

#### What you expected to happen: 
I expected that the "antenna" on the detector to be colored like all the other devices from RS when applying a dye to it.

#### Steps to reproduce:
1. Place a detector in top of a exporter.
2. Apply item and amount in the detector.
3. Set mode to "Emit signal when above the amount"
4. Try to apply a dye (magenta in my case) to the detector
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.1.24
- Refined Storage: 

Does this issue occur on a server? Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment] 2021-06-04 10:53
Duplicate of #2899

**Closed by Darkere** 2021-06-04 10:53 UTC
