### ISSUE TITLE
Fluid crafting and drawer visibility

### ISSUE THREAD

**Issue by kri5kringle** [refinedmods/refinedstorage#2836] opened 2021-01-16 11:36 UTC
well to start off i have two bugs to report. not sure if they have to be in separate posts or not

#### What happens:
with a fluid storage block or disk, you will be able to pull a bucket of said fluid from a fluid grid. 
If you attempt to craft a recipe from the crafting grid with for example lava, you will not be able to craft with lava. the crafting grid cannot find the lava to craft with. if you have a recipe with lava in it and attempt to craft it you will be told you cant. 
#### What you expected to happen:
lava in system. I expect to be able to craft with lava. or tell my system to craft a recipe with lava
#### Steps to reproduce:
1. add fluid storage to your system disk or block.
2.fill storage with liquid
3.attempt to craft with liquid.
...

#### What happens: whenever loading a save your items in drawers attached to an external storage will not appear.
However if you attempt to craft with an item from your drawers it will appear red and say you dont have any, but if you shift click a recipe into the grid it will appear and be able to craft. 
this also happens after going to another dimension. with or without chunks loading

#### Steps to reproduce:
1. attach external storage to drawer or drawer controller
2.travel to another dimension and back, or quit the game then re open your save
3.items will not appear in grid. 
4. attempt to craft with an item attached to storage
5. craft is successful
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.16
- Forge:1.16.4-gecholib-3.0.0
- Refined Storage:1.9.11
-Modpack Dw20 1.16-1.3.1
Does this issue occur on a server? [yes/no]
no
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by uecasm** [comment] 2021-01-23 11:45
The first issue seems to be due to a change in how the vanilla crafting recipe processing works, and may have been intentional.

Essentially the fluids can now only directly be used in processing patterns; for crafting patterns (where it uses a bucket of fluid) you have to actually craft a bucket of fluid as a processing pattern (either via vanilla dispenser or by some machine that can fill buckets).  Once you've set up this extra pattern (and put it into a machine), you'll be able to do the original crafting operation using the stored fluid.

This is a workable workaround, but it would be very nice if it could be handled internally instead -- given that the Fluid Grid can do it, it doesn't seem unreasonable that the crafting system should know how to fill buckets without needing an explicit pattern.

Having said that, it's possible that this change might be to support differences in behaviour of buckets -- for example while most buckets are returned after the craft, clay bucket + lava does not return the bucket, for example.  An explicit pattern helps to capture which bucket you intended to use and what ends up happening to it.


Regarding your issue with the external storage, I've heard that reported before, but I'm on the same modpack and I've never had that issue.  I wonder if perhaps it's related to the specific placement of the external storage and/or drawer controller?  I always have the controller under the drawers and the external storage under that, and in a force-loaded chunk.  Do you have something different; perhaps a different orientation, crossing a chunk boundary, or not force loaded?

**Comment by kri5kringle** [comment] 2021-01-24 04:17
with refined storage, placing the external storage on the bottom of the drawer controller did not make a difference. (I previously had it on the side of the controller) With each relaunch of the pack i have to manually re connect the controller. Yes my whole base is chunk loaded however it is crossing chunk lines.

**Comment by Darkere** [comment] 2021-01-31 15:18
Duplicate of #2636

**Closed by Darkere** 2021-01-31 15:18 UTC
