### ISSUE TITLE
Crash after pasting some RS blocks using Building Gadgets copy-paste tool

### ISSUE THREAD

**Issue by Quinteger** [refinedmods/refinedstorage#3104] opened 2021-10-15 17:44 UTC
#### Issue description:
I pasted a small contraption consisting of a network receiver, cable, and external storage going into a drawer controller and some drawer controller slaves next to it. I didn't actually have a network receiver or any drawer controllers in my inventory.

#### What happens:
I caught a glimpse of cable+external storage successfully being pasted and the server crashed.
https://gist.github.com/Quinteger/038b01a4186e1a24049bae33420a3b70
I am not sure which mod is responsible for the crash, so I am posting it here since the top stack frames comes from RS.

#### What you expected to happen:
Definitely not crashing the server

#### Steps to reproduce:
1. This is the contraption I copied (ignore oak drawers):
![image](https://user-images.githubusercontent.com/7419124/137530043-a84d35b8-deed-4b3f-94d1-31d937ad8242.png)
Because of weird interactions with right-click, you may need to add some plain blocks to be able to copy it properly
2. Paste without having any drawer controllers and network receivers

#### Version (make sure you are on the latest version before reporting):

- Modpack: Valhelsia 3 v3.4.4
- Minecraft: 1.16.5
- Forge: 36.2.8
- Refined Storage: 1.9.15

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/Quinteger/038b01a4186e1a24049bae33420a3b70

**Comment by Invy55** [comment] 2021-11-24 15:40
Wow this bug is still going on... #2842

**Comment by MACSkeptic** [comment] 2021-11-30 20:48
I just ran into _exactly_ this earlier this week as well

**Comment by KennethWussmann** [comment] 2021-12-21 12:51
I had the same multiple times now. The problem is also that when the area is chunkloaded the server won't start anymore. It's now stuck in a restart loop, because the exception occurs over and over again. 
This is by the way a consistent way to crash any public server with this combination. I would love to see a better approach than just failing. For example breaking the block in question and dropping it's item.

**Comment by raoulvdberge** [comment] 2022-03-26 07:46
This won't be fixed for RS 1.

**Closed** 2022-03-26 07:46 UTC
Labels: bug
